// Wörterbuch — A1 Vokabeldaten
// Jedes Wort hat eine eindeutige ID (a1-001, a1-002, ...) für Fortschritts-Tracking.
// 20 Wörter = 1 Sub-Level. Reihenfolge im Array bestimmt die Sub-Level-Zuordnung.

export const vocabA1 = [
  // Sub-Level 1 — Begrüßung & Pronomen (001–020)
  { id: "a1-001", german: "Hallo", bengali: "হ্যালো", example: "Hallo! Wie geht's?" },
  { id: "a1-002", german: "Guten Tag", bengali: "শুভ দিন", example: "Guten Tag, Frau Müller." },
  { id: "a1-003", german: "Guten Morgen", bengali: "শুভ সকাল", example: "Guten Morgen! Hast du gut geschlafen?" },
  { id: "a1-004", german: "Guten Abend", bengali: "শুভ সন্ধ্যা", example: "Guten Abend, wie war dein Tag?" },
  { id: "a1-005", german: "Gute Nacht", bengali: "শুভ রাত্রি", example: "Gute Nacht, schlaf gut!" },
  { id: "a1-006", german: "Auf Wiedersehen", bengali: "বিদায়", example: "Auf Wiedersehen, bis morgen!" },
  { id: "a1-007", german: "Tschüss", bengali: "বাই", example: "Tschüss, bis später!" },
  { id: "a1-008", german: "Bitte", bengali: "দয়া করে", example: "Bitte, setzen Sie sich." },
  { id: "a1-009", german: "Danke", bengali: "ধন্যবাদ", example: "Danke für deine Hilfe." },
  { id: "a1-010", german: "Ja", bengali: "হ্যাঁ", example: "Ja, das ist richtig." },
  { id: "a1-011", german: "Nein", bengali: "না", example: "Nein, das stimmt nicht." },
  { id: "a1-012", german: "Entschuldigung", bengali: "মাফ করবেন", example: "Entschuldigung, wo ist der Bahnhof?" },
  { id: "a1-013", german: "ich", bengali: "আমি", example: "Ich lerne Deutsch." },
  { id: "a1-014", german: "du", bengali: "তুমি", example: "Wie heißt du?" },
  { id: "a1-015", german: "er", bengali: "সে (পুরুষ)", example: "Er wohnt in Berlin." },
  { id: "a1-016", german: "sie", bengali: "সে (মহিলা)", example: "Sie spricht Deutsch." },
  { id: "a1-017", german: "es", bengali: "এটা", example: "Es ist kalt heute." },
  { id: "a1-018", german: "wir", bengali: "আমরা", example: "Wir lernen zusammen." },
  { id: "a1-019", german: "ihr", bengali: "তোমরা", example: "Wo wohnt ihr?" },
  { id: "a1-020", german: "Sie", bengali: "আপনি", example: "Wie heißen Sie?" },

  // Sub-Level 2 — Zahlen 0–19 (021–040)
  { id: "a1-021", german: "null", bengali: "শূন্য", example: "Meine Note ist null Fehler." },
  { id: "a1-022", german: "eins", bengali: "এক", example: "Ich habe nur eins." },
  { id: "a1-023", german: "zwei", bengali: "দুই", example: "Ich habe zwei Brüder." },
  { id: "a1-024", german: "drei", bengali: "তিন", example: "Wir sind drei Personen." },
  { id: "a1-025", german: "vier", bengali: "চার", example: "Der Tisch hat vier Beine." },
  { id: "a1-026", german: "fünf", bengali: "পাঁচ", example: "Ich warte fünf Minuten." },
  { id: "a1-027", german: "sechs", bengali: "ছয়", example: "Der Kurs dauert sechs Wochen." },
  { id: "a1-028", german: "sieben", bengali: "সাত", example: "Die Woche hat sieben Tage." },
  { id: "a1-029", german: "acht", bengali: "আট", example: "Ich schlafe acht Stunden." },
  { id: "a1-030", german: "neun", bengali: "নয়", example: "Der Zug kommt um neun." },
  { id: "a1-031", german: "zehn", bengali: "দশ", example: "Ich habe zehn Euro." },
  { id: "a1-032", german: "elf", bengali: "এগারো", example: "Die Uhr zeigt elf." },
  { id: "a1-033", german: "zwölf", bengali: "বারো", example: "Ein Tag hat zwölf Stunden Licht." },
  { id: "a1-034", german: "dreizehn", bengali: "তেরো", example: "Sie ist dreizehn Jahre alt." },
  { id: "a1-035", german: "vierzehn", bengali: "চৌদ্দ", example: "Der Monat hat vierzehn Tage Urlaub." },
  { id: "a1-036", german: "fünfzehn", bengali: "পনেরো", example: "Wir warten fünfzehn Minuten." },
  { id: "a1-037", german: "sechzehn", bengali: "ষোলো", example: "Er ist sechzehn Jahre alt." },
  { id: "a1-038", german: "siebzehn", bengali: "সতেরো", example: "Sie kommt um siebzehn Uhr." },
  { id: "a1-039", german: "achtzehn", bengali: "আঠারো", example: "Mit achtzehn darf man wählen." },
  { id: "a1-040", german: "neunzehn", bengali: "উনিশ", example: "Das Zimmer kostet neunzehn Euro." },

  // Sub-Level 3 — Familie (041–060)
  { id: "a1-041", german: "die Mutter", bengali: "মা", example: "Meine Mutter kocht gut." },
  { id: "a1-042", german: "der Vater", bengali: "বাবা", example: "Mein Vater arbeitet viel." },
  { id: "a1-043", german: "der Sohn", bengali: "ছেলে", example: "Mein Sohn spielt Fußball." },
  { id: "a1-044", german: "die Tochter", bengali: "মেয়ে", example: "Meine Tochter lacht viel." },
  { id: "a1-045", german: "der Bruder", bengali: "ভাই", example: "Mein Bruder studiert." },
  { id: "a1-046", german: "die Schwester", bengali: "বোন", example: "Meine Schwester ist jung." },
  { id: "a1-047", german: "die Großmutter", bengali: "দাদি/নানি", example: "Meine Großmutter ist alt." },
  { id: "a1-048", german: "der Großvater", bengali: "দাদা/নানা", example: "Mein Großvater liest viel." },
  { id: "a1-049", german: "der Onkel", bengali: "চাচা/মামা", example: "Mein Onkel ist nett." },
  { id: "a1-050", german: "die Tante", bengali: "চাচি/খালা", example: "Meine Tante kocht gut." },
  { id: "a1-051", german: "der Cousin", bengali: "চাচাতো/মামাতো ভাই", example: "Mein Cousin studiert." },
  { id: "a1-052", german: "die Cousine", bengali: "চাচাতো/মামাতো বোন", example: "Meine Cousine tanzt gut." },
  { id: "a1-053", german: "die Eltern", bengali: "পিতামাতা", example: "Meine Eltern wohnen in Dhaka." },
  { id: "a1-054", german: "das Kind", bengali: "শিশু", example: "Das Kind spielt draußen." },
  { id: "a1-055", german: "das Baby", bengali: "নবজাতক", example: "Das Baby schläft." },
  { id: "a1-056", german: "der Mann", bengali: "পুরুষ/স্বামী", example: "Ihr Mann ist Arzt." },
  { id: "a1-057", german: "die Frau", bengali: "মহিলা/স্ত্রী", example: "Meine Frau ist Lehrerin." },
  { id: "a1-058", german: "die Familie", bengali: "পরিবার", example: "Meine Familie ist groß." },
  { id: "a1-059", german: "der/die Verwandte", bengali: "আত্মীয়", example: "Er ist ein Verwandter von mir." },
  { id: "a1-060", german: "der Enkel", bengali: "নাতি", example: "Mein Enkel ist klein." },

  // Sub-Level 4 — Farben & Adjektive (061–080)
  { id: "a1-061", german: "rot", bengali: "লাল", example: "Das Auto ist rot." },
  { id: "a1-062", german: "blau", bengali: "নীল", example: "Der Himmel ist blau." },
  { id: "a1-063", german: "grün", bengali: "সবুজ", example: "Das Gras ist grün." },
  { id: "a1-064", german: "gelb", bengali: "হলুদ", example: "Die Sonne ist gelb." },
  { id: "a1-065", german: "schwarz", bengali: "কালো", example: "Die Katze ist schwarz." },
  { id: "a1-066", german: "weiß", bengali: "সাদা", example: "Der Schnee ist weiß." },
  { id: "a1-067", german: "braun", bengali: "বাদামি", example: "Der Tisch ist braun." },
  { id: "a1-068", german: "orange", bengali: "কমলা", example: "Die Orange ist orange." },
  { id: "a1-069", german: "rosa", bengali: "গোলাপি", example: "Das Kleid ist rosa." },
  { id: "a1-070", german: "grau", bengali: "ধূসর", example: "Der Himmel ist grau." },
  { id: "a1-071", german: "lila", bengali: "বেগুনি", example: "Die Blume ist lila." },
  { id: "a1-072", german: "bunt", bengali: "রঙিন", example: "Das Bild ist sehr bunt." },
  { id: "a1-073", german: "hell", bengali: "উজ্জ্বল", example: "Das Zimmer ist hell." },
  { id: "a1-074", german: "dunkel", bengali: "অন্ধকার", example: "Der Flur ist dunkel." },
  { id: "a1-075", german: "groß", bengali: "বড়", example: "Das Haus ist groß." },
  { id: "a1-076", german: "klein", bengali: "ছোট", example: "Das Kind ist klein." },
  { id: "a1-077", german: "neu", bengali: "নতুন", example: "Das Auto ist neu." },
  { id: "a1-078", german: "alt", bengali: "পুরনো", example: "Das Buch ist alt." },
  { id: "a1-079", german: "schön", bengali: "সুন্দর", example: "Das Wetter ist schön." },
  { id: "a1-080", german: "hässlich", bengali: "কুৎসিত", example: "Das Bild ist hässlich." },

  // Sub-Level 5 — Essen & Trinken (081–100)
  { id: "a1-081", german: "das Brot", bengali: "রুটি", example: "Das Brot ist frisch." },
  { id: "a1-082", german: "das Wasser", bengali: "পানি", example: "Das Wasser ist kalt." },
  { id: "a1-083", german: "die Milch", bengali: "দুধ", example: "Die Milch ist frisch." },
  { id: "a1-084", german: "der Apfel", bengali: "আপেল", example: "Der Apfel ist süß." },
  { id: "a1-085", german: "die Banane", bengali: "কলা", example: "Die Banane ist gelb." },
  { id: "a1-086", german: "der Kaffee", bengali: "কফি", example: "Der Kaffee ist heiß." },
  { id: "a1-087", german: "der Tee", bengali: "চা", example: "Der Tee ist warm." },
  { id: "a1-088", german: "der Reis", bengali: "ভাত/চাল", example: "Der Reis ist fertig." },
  { id: "a1-089", german: "der Fisch", bengali: "মাছ", example: "Der Fisch ist frisch." },
  { id: "a1-090", german: "das Fleisch", bengali: "মাংস", example: "Das Fleisch ist teuer." },
  { id: "a1-091", german: "das Gemüse", bengali: "শাকসবজি", example: "Das Gemüse ist gesund." },
  { id: "a1-092", german: "das Obst", bengali: "ফল", example: "Das Obst ist süß." },
  { id: "a1-093", german: "der Käse", bengali: "চিজ/পনির", example: "Der Käse schmeckt gut." },
  { id: "a1-094", german: "das Ei", bengali: "ডিম", example: "Das Ei ist frisch." },
  { id: "a1-095", german: "der Zucker", bengali: "চিনি", example: "Der Zucker ist süß." },
  { id: "a1-096", german: "das Salz", bengali: "লবণ", example: "Das Salz fehlt hier." },
  { id: "a1-097", german: "die Butter", bengali: "মাখন", example: "Die Butter ist kalt." },
  { id: "a1-098", german: "die Suppe", bengali: "স্যুপ", example: "Die Suppe ist heiß." },
  { id: "a1-099", german: "der Kuchen", bengali: "কেক", example: "Der Kuchen ist süß." },
  { id: "a1-100", german: "der Saft", bengali: "জুস", example: "Der Saft ist kalt." },

  // Sub-Level 6 — Zahlen 20+ & Ordnungszahlen (101–120)
  { id: "a1-101", german: "zwanzig", bengali: "বিশ", example: "Er ist zwanzig Jahre alt." },
  { id: "a1-102", german: "einundzwanzig", bengali: "একুশ", example: "Ich habe einundzwanzig Bücher." },
  { id: "a1-103", german: "dreißig", bengali: "ত্রিশ", example: "Die Stadt hat dreißig Schulen." },
  { id: "a1-104", german: "vierzig", bengali: "চল্লিশ", example: "Mein Vater ist vierzig Jahre alt." },
  { id: "a1-105", german: "fünfzig", bengali: "পঞ্চাশ", example: "Das Zimmer kostet fünfzig Euro." },
  { id: "a1-106", german: "sechzig", bengali: "ষাট", example: "Die Reise dauert sechzig Minuten." },
  { id: "a1-107", german: "siebzig", bengali: "সত্তর", example: "Meine Oma ist siebzig Jahre alt." },
  { id: "a1-108", german: "achtzig", bengali: "আশি", example: "Der Kurs hat achtzig Studenten." },
  { id: "a1-109", german: "neunzig", bengali: "নব্বই", example: "Das Auto fährt neunzig Kilometer." },
  { id: "a1-110", german: "hundert", bengali: "একশো", example: "Das kostet hundert Euro." },
  { id: "a1-111", german: "zweihundert", bengali: "দুইশো", example: "Ich habe zweihundert Euro gespart." },
  { id: "a1-112", german: "fünfhundert", bengali: "পাঁচশো", example: "Der Tisch kostet fünfhundert Euro." },
  { id: "a1-113", german: "tausend", bengali: "এক হাজার", example: "Die Stadt hat tausend Einwohner." },
  { id: "a1-114", german: "die Million", bengali: "মিলিয়ন", example: "Die Stadt hat eine Million Einwohner." },
  { id: "a1-115", german: "erste", bengali: "প্রথম", example: "Das ist mein erster Tag." },
  { id: "a1-116", german: "zweite", bengali: "দ্বিতীয়", example: "Sie wohnt im zweiten Stock." },
  { id: "a1-117", german: "dritte", bengali: "তৃতীয়", example: "Er ist der dritte Sohn." },
  { id: "a1-118", german: "letzte", bengali: "সর্বশেষ", example: "Das ist die letzte Frage." },
  { id: "a1-119", german: "nächste", bengali: "পরবর্তী", example: "Wann ist der nächste Bus?" },
  { id: "a1-120", german: "die Zahl", bengali: "সংখ্যা", example: "Wie heißt diese Zahl?" },

  // Sub-Level 7 — Wochentage & Monate (121–140)
  { id: "a1-121", german: "der Montag", bengali: "সোমবার", example: "Am Montag arbeite ich." },
  { id: "a1-122", german: "der Dienstag", bengali: "মঙ্গলবার", example: "Am Dienstag lerne ich Deutsch." },
  { id: "a1-123", german: "der Mittwoch", bengali: "বুধবার", example: "Am Mittwoch gehe ich einkaufen." },
  { id: "a1-124", german: "der Donnerstag", bengali: "বৃহস্পতিবার", example: "Am Donnerstag koche ich." },
  { id: "a1-125", german: "der Freitag", bengali: "শুক্রবার", example: "Am Freitag ist Kurs." },
  { id: "a1-126", german: "der Samstag", bengali: "শনিবার", example: "Am Samstag schlafe ich lang." },
  { id: "a1-127", german: "der Sonntag", bengali: "রবিবার", example: "Am Sonntag besuche ich Familie." },
  { id: "a1-128", german: "die Woche", bengali: "সপ্তাহ", example: "Die Woche hat sieben Tage." },
  { id: "a1-129", german: "das Wochenende", bengali: "সাপ্তাহান্ত", example: "Das Wochenende ist schön." },
  { id: "a1-130", german: "der Januar", bengali: "জানুয়ারি", example: "Im Januar ist es kalt." },
  { id: "a1-131", german: "der Februar", bengali: "ফেব্রুয়ারি", example: "Im Februar schneit es." },
  { id: "a1-132", german: "der März", bengali: "মার্চ", example: "Im März wird es wärmer." },
  { id: "a1-133", german: "der April", bengali: "এপ্রিল", example: "Im April regnet es oft." },
  { id: "a1-134", german: "der Mai", bengali: "মে", example: "Im Mai blühen die Blumen." },
  { id: "a1-135", german: "der Juni", bengali: "জুন", example: "Im Juni ist es warm." },
  { id: "a1-136", german: "der Juli", bengali: "জুলাই", example: "Im Juli fahre ich in Urlaub." },
  { id: "a1-137", german: "der August", bengali: "আগস্ট", example: "Im August ist es heiß." },
  { id: "a1-138", german: "der September", bengali: "সেপ্টেম্বর", example: "Im September beginnt die Schule." },
  { id: "a1-139", german: "der Oktober", bengali: "অক্টোবর", example: "Im Oktober wird es kühler." },
  { id: "a1-140", german: "der November", bengali: "নভেম্বর", example: "Im November regnet es viel." },

  // Sub-Level 8 — Uhrzeit & Zeit (141–160)
  { id: "a1-141", german: "die Uhr", bengali: "ঘড়ি/সময়", example: "Wie viel Uhr ist es?" },
  { id: "a1-142", german: "die Minute", bengali: "মিনিট", example: "Warte eine Minute!" },
  { id: "a1-143", german: "die Stunde", bengali: "ঘণ্টা", example: "Eine Stunde hat sechzig Minuten." },
  { id: "a1-144", german: "die Sekunde", bengali: "সেকেন্ড", example: "Eine Minute hat sechzig Sekunden." },
  { id: "a1-145", german: "der Morgen", bengali: "সকাল", example: "Der Morgen ist schön." },
  { id: "a1-146", german: "der Mittag", bengali: "দুপুর", example: "Um Mittag esse ich." },
  { id: "a1-147", german: "der Nachmittag", bengali: "বিকাল", example: "Am Nachmittag arbeite ich." },
  { id: "a1-148", german: "der Abend", bengali: "সন্ধ্যা", example: "Der Abend ist ruhig." },
  { id: "a1-149", german: "die Nacht", bengali: "রাত", example: "Die Nacht ist kalt." },
  { id: "a1-150", german: "heute", bengali: "আজ", example: "Heute ist Montag." },
  { id: "a1-151", german: "morgen", bengali: "আগামীকাল", example: "Morgen komme ich." },
  { id: "a1-152", german: "gestern", bengali: "গতকাল", example: "Gestern war es kalt." },
  { id: "a1-153", german: "jetzt", bengali: "এখন", example: "Ich lerne jetzt Deutsch." },
  { id: "a1-154", german: "immer", bengali: "সবসময়", example: "Er ist immer pünktlich." },
  { id: "a1-155", german: "manchmal", bengali: "কখনো কখনো", example: "Manchmal koche ich selbst." },
  { id: "a1-156", german: "oft", bengali: "প্রায়ই", example: "Ich gehe oft spazieren." },
  { id: "a1-157", german: "nie", bengali: "কখনো না", example: "Ich trinke nie Alkohol." },
  { id: "a1-158", german: "früh", bengali: "সকাল সকাল", example: "Ich stehe früh auf." },
  { id: "a1-159", german: "spät", bengali: "দেরিতে", example: "Er kommt immer spät." },
  { id: "a1-160", german: "der Tag", bengali: "দিন", example: "Der Tag ist schön." },

  // Sub-Level 9 — Körperteile (161–180)
  { id: "a1-161", german: "der Kopf", bengali: "মাথা", example: "Mein Kopf tut weh." },
  { id: "a1-162", german: "das Haar", bengali: "চুল", example: "Ihr Haar ist lang." },
  { id: "a1-163", german: "das Auge", bengali: "চোখ", example: "Sein Auge ist blau." },
  { id: "a1-164", german: "die Nase", bengali: "নাক", example: "Meine Nase läuft." },
  { id: "a1-165", german: "der Mund", bengali: "মুখ", example: "Sein Mund ist klein." },
  { id: "a1-166", german: "das Ohr", bengali: "কান", example: "Mein Ohr tut weh." },
  { id: "a1-167", german: "der Zahn", bengali: "দাঁত", example: "Mein Zahn tut weh." },
  { id: "a1-168", german: "der Hals", bengali: "গলা", example: "Mein Hals tut weh." },
  { id: "a1-169", german: "die Schulter", bengali: "কাঁধ", example: "Meine Schulter schmerzt." },
  { id: "a1-170", german: "der Arm", bengali: "হাত (বাহু)", example: "Mein Arm ist gebrochen." },
  { id: "a1-171", german: "die Hand", bengali: "হাত", example: "Meine Hand ist kalt." },
  { id: "a1-172", german: "der Finger", bengali: "আঙুল", example: "Mein Finger tut weh." },
  { id: "a1-173", german: "der Bauch", bengali: "পেট", example: "Mein Bauch tut weh." },
  { id: "a1-174", german: "der Rücken", bengali: "পিঠ", example: "Mein Rücken schmerzt." },
  { id: "a1-175", german: "das Bein", bengali: "পা (পায়ের অংশ)", example: "Mein Bein tut weh." },
  { id: "a1-176", german: "das Knie", bengali: "হাঁটু", example: "Mein Knie tut weh." },
  { id: "a1-177", german: "der Fuß", bengali: "পা", example: "Mein Fuß tut weh." },
  { id: "a1-178", german: "das Herz", bengali: "হৃদয়", example: "Mein Herz schlägt schnell." },
  { id: "a1-179", german: "die Haut", bengali: "চামড়া", example: "Die Haut ist trocken." },
  { id: "a1-180", german: "der Körper", bengali: "শরীর", example: "Mein Körper ist fit." },

  // Sub-Level 10 — Kleidung (181–200)
  { id: "a1-181", german: "die Kleidung", bengali: "পোশাক", example: "Die Kleidung ist schön." },
  { id: "a1-182", german: "die Jacke", bengali: "জ্যাকেট", example: "Die Jacke ist warm." },
  { id: "a1-183", german: "der Mantel", bengali: "কোট", example: "Der Mantel ist lang." },
  { id: "a1-184", german: "das Hemd", bengali: "শার্ট", example: "Das Hemd ist weiß." },
  { id: "a1-185", german: "die Bluse", bengali: "ব্লাউজ", example: "Die Bluse ist neu." },
  { id: "a1-186", german: "der Pullover", bengali: "সোয়েটার", example: "Der Pullover ist warm." },
  { id: "a1-187", german: "die Hose", bengali: "প্যান্ট", example: "Die Hose ist blau." },
  { id: "a1-188", german: "der Rock", bengali: "স্কার্ট", example: "Der Rock ist kurz." },
  { id: "a1-189", german: "das Kleid", bengali: "ড্রেস", example: "Das Kleid ist schön." },
  { id: "a1-190", german: "die Socke", bengali: "মোজা", example: "Die Socke ist warm." },
  { id: "a1-191", german: "der Schuh", bengali: "জুতা", example: "Der Schuh ist neu." },
  { id: "a1-192", german: "der Stiefel", bengali: "বুট", example: "Der Stiefel ist schwer." },
  { id: "a1-193", german: "die Mütze", bengali: "টুপি", example: "Die Mütze ist warm." },
  { id: "a1-194", german: "der Schal", bengali: "স্কার্ফ", example: "Der Schal ist lang." },
  { id: "a1-195", german: "der Handschuh", bengali: "হাতের গ্লাভস", example: "Die Handschuhe sind warm." },
  { id: "a1-196", german: "die Brille", bengali: "চশমা", example: "Die Brille ist neu." },
  { id: "a1-197", german: "die Tasche", bengali: "ব্যাগ", example: "Die Tasche ist schwer." },
  { id: "a1-198", german: "der Gürtel", bengali: "বেল্ট", example: "Der Gürtel ist neu." },
  { id: "a1-199", german: "der Schmuck", bengali: "অলংকার", example: "Der Schmuck ist teuer." },
  { id: "a1-200", german: "die Größe", bengali: "সাইজ", example: "Welche Größe haben Sie?" },

  // Sub-Level 11 — Haus & Möbel (201–220)
  { id: "a1-201", german: "das Haus", bengali: "বাড়ি", example: "Das Haus ist groß." },
  { id: "a1-202", german: "die Wohnung", bengali: "অ্যাপার্টমেন্ট", example: "Meine Wohnung ist klein." },
  { id: "a1-203", german: "das Zimmer", bengali: "রুম", example: "Das Zimmer ist hell." },
  { id: "a1-204", german: "die Küche", bengali: "রান্নাঘর", example: "Die Küche ist modern." },
  { id: "a1-205", german: "das Bad", bengali: "বাথরুম", example: "Das Bad ist sauber." },
  { id: "a1-206", german: "das Wohnzimmer", bengali: "বসার ঘর", example: "Das Wohnzimmer ist gemütlich." },
  { id: "a1-207", german: "das Schlafzimmer", bengali: "শোবার ঘর", example: "Das Schlafzimmer ist ruhig." },
  { id: "a1-208", german: "der Balkon", bengali: "বারান্দা", example: "Der Balkon ist schön." },
  { id: "a1-209", german: "der Garten", bengali: "বাগান", example: "Der Garten ist grün." },
  { id: "a1-210", german: "die Tür", bengali: "দরজা", example: "Die Tür ist offen." },
  { id: "a1-211", german: "das Fenster", bengali: "জানালা", example: "Das Fenster ist groß." },
  { id: "a1-212", german: "der Tisch", bengali: "টেবিল", example: "Der Tisch ist neu." },
  { id: "a1-213", german: "der Stuhl", bengali: "চেয়ার", example: "Der Stuhl ist bequem." },
  { id: "a1-214", german: "das Sofa", bengali: "সোফা", example: "Das Sofa ist weich." },
  { id: "a1-215", german: "das Bett", bengali: "বিছানা", example: "Das Bett ist groß." },
  { id: "a1-216", german: "der Schrank", bengali: "আলমারি", example: "Der Schrank ist voll." },
  { id: "a1-217", german: "das Regal", bengali: "তাক", example: "Das Regal ist leer." },
  { id: "a1-218", german: "die Lampe", bengali: "বাতি", example: "Die Lampe ist hell." },
  { id: "a1-219", german: "der Spiegel", bengali: "আয়না", example: "Der Spiegel ist groß." },
  { id: "a1-220", german: "der Teppich", bengali: "কার্পেট", example: "Der Teppich ist weich." },

  // Sub-Level 12 — Küche & Geschirr (221–240)
  { id: "a1-221", german: "der Kühlschrank", bengali: "ফ্রিজ", example: "Der Kühlschrank ist kalt." },
  { id: "a1-222", german: "der Herd", bengali: "চুলা", example: "Der Herd ist heiß." },
  { id: "a1-223", german: "die Pfanne", bengali: "ফ্রাইং প্যান", example: "Die Pfanne ist heiß." },
  { id: "a1-224", german: "der Topf", bengali: "হাঁড়ি", example: "Der Topf ist groß." },
  { id: "a1-225", german: "das Messer", bengali: "ছুরি", example: "Das Messer ist scharf." },
  { id: "a1-226", german: "die Gabel", bengali: "কাঁটাচামচ", example: "Die Gabel ist sauber." },
  { id: "a1-227", german: "der Löffel", bengali: "চামচ", example: "Der Löffel ist groß." },
  { id: "a1-228", german: "der Teller", bengali: "প্লেট", example: "Der Teller ist voll." },
  { id: "a1-229", german: "die Tasse", bengali: "কাপ", example: "Die Tasse ist heiß." },
  { id: "a1-230", german: "das Glas", bengali: "গ্লাস", example: "Das Glas ist kalt." },
  { id: "a1-231", german: "die Schüssel", bengali: "বাটি", example: "Die Schüssel ist groß." },
  { id: "a1-232", german: "die Serviette", bengali: "নাপকিন", example: "Die Serviette ist sauber." },
  { id: "a1-233", german: "die Spülmaschine", bengali: "ডিশওয়াশার", example: "Die Spülmaschine läuft." },
  { id: "a1-234", german: "die Waschmaschine", bengali: "ওয়াশিং মেশিন", example: "Die Waschmaschine läuft." },
  { id: "a1-235", german: "backen", bengali: "বেক করা", example: "Ich backe einen Kuchen." },
  { id: "a1-236", german: "braten", bengali: "ভাজা", example: "Ich brate das Fleisch." },
  { id: "a1-237", german: "kochen", bengali: "রান্না করা", example: "Wer kocht heute?" },
  { id: "a1-238", german: "schneiden", bengali: "কাটা", example: "Ich schneide das Gemüse." },
  { id: "a1-239", german: "das Rezept", bengali: "রেসিপি", example: "Das Rezept ist einfach." },
  { id: "a1-240", german: "die Mahlzeit", bengali: "খাবারের সময়", example: "Guten Appetit zur Mahlzeit!" },

  // Sub-Level 13 — Stadt & Orte (241–260)
  { id: "a1-241", german: "die Stadt", bengali: "শহর", example: "Hamburg ist eine große Stadt." },
  { id: "a1-242", german: "das Dorf", bengali: "গ্রাম", example: "Das Dorf ist klein." },
  { id: "a1-243", german: "die Straße", bengali: "রাস্তা", example: "Die Straße ist lang." },
  { id: "a1-244", german: "der Platz", bengali: "চত্বর", example: "Der Platz ist schön." },
  { id: "a1-245", german: "die Brücke", bengali: "সেতু", example: "Die Brücke ist alt." },
  { id: "a1-246", german: "der Park", bengali: "পার্ক", example: "Der Park ist grün." },
  { id: "a1-247", german: "das Museum", bengali: "জাদুঘর", example: "Das Museum ist interessant." },
  { id: "a1-248", german: "die Kirche", bengali: "গির্জা", example: "Die Kirche ist alt." },
  { id: "a1-249", german: "das Krankenhaus", bengali: "হাসপাতাল", example: "Das Krankenhaus ist groß." },
  { id: "a1-250", german: "die Schule", bengali: "স্কুল", example: "Die Schule beginnt um 8." },
  { id: "a1-251", german: "die Universität", bengali: "বিশ্ববিদ্যালয়", example: "Die Universität ist bekannt." },
  { id: "a1-252", german: "der Bahnhof", bengali: "রেলস্টেশন", example: "Der Bahnhof ist groß." },
  { id: "a1-253", german: "der Flughafen", bengali: "বিমানবন্দর", example: "Der Flughafen ist weit." },
  { id: "a1-254", german: "die Bank", bengali: "ব্যাংক", example: "Die Bank öffnet um 9." },
  { id: "a1-255", german: "die Post", bengali: "ডাকঘর", example: "Die Post ist geschlossen." },
  { id: "a1-256", german: "die Apotheke", bengali: "ওষুধের দোকান", example: "Die Apotheke ist offen." },
  { id: "a1-257", german: "der Supermarkt", bengali: "সুপারমার্কেট", example: "Der Supermarkt ist nah." },
  { id: "a1-258", german: "das Restaurant", bengali: "রেস্তোরাঁ", example: "Das Restaurant ist voll." },
  { id: "a1-259", german: "das Hotel", bengali: "হোটেল", example: "Das Hotel ist teuer." },
  { id: "a1-260", german: "das Kino", bengali: "সিনেমা হল", example: "Das Kino ist neu." },

  // Sub-Level 14 — Verkehr & Transport (261–280)
  { id: "a1-261", german: "das Auto", bengali: "গাড়ি", example: "Das Auto ist rot." },
  { id: "a1-262", german: "der Bus", bengali: "বাস", example: "Der Bus ist voll." },
  { id: "a1-263", german: "der Zug", bengali: "ট্রেন", example: "Der Zug kommt gleich." },
  { id: "a1-264", german: "die U-Bahn", bengali: "মেট্রো", example: "Die U-Bahn ist schnell." },
  { id: "a1-265", german: "die Straßenbahn", bengali: "ট্রাম", example: "Die Straßenbahn kommt gleich." },
  { id: "a1-266", german: "das Fahrrad", bengali: "সাইকেল", example: "Das Fahrrad ist neu." },
  { id: "a1-267", german: "das Motorrad", bengali: "মোটরসাইকেল", example: "Das Motorrad ist schnell." },
  { id: "a1-268", german: "das Taxi", bengali: "ট্যাক্সি", example: "Ich nehme ein Taxi." },
  { id: "a1-269", german: "das Flugzeug", bengali: "বিমান", example: "Das Flugzeug ist neu." },
  { id: "a1-270", german: "das Schiff", bengali: "জাহাজ", example: "Das Schiff ist groß." },
  { id: "a1-271", german: "fahren", bengali: "চালানো/যাওয়া", example: "Ich fahre nach Hamburg." },
  { id: "a1-272", german: "gehen", bengali: "হাঁটা/যাওয়া", example: "Ich gehe in die Stadt." },
  { id: "a1-273", german: "fliegen", bengali: "উড়া", example: "Wir fliegen nach Berlin." },
  { id: "a1-274", german: "die Haltestelle", bengali: "বাস স্টপ", example: "Die Haltestelle ist hier." },
  { id: "a1-275", german: "der Bahnsteig", bengali: "প্ল্যাটফর্ম", example: "Der Bahnsteig ist voll." },
  { id: "a1-276", german: "das Ticket", bengali: "টিকিট", example: "Das Ticket ist teuer." },
  { id: "a1-277", german: "die Fahrkarte", bengali: "টিকিট", example: "Die Fahrkarte ist billig." },
  { id: "a1-278", german: "ankommen", bengali: "পৌঁছানো", example: "Wir kommen morgen an." },
  { id: "a1-279", german: "abfahren", bengali: "রওনা হওয়া", example: "Der Zug fährt um 8 ab." },
  { id: "a1-280", german: "der Stau", bengali: "যানজট", example: "Der Stau ist lang." },

  // Sub-Level 15 — Berufe (281–300)
  { id: "a1-281", german: "der Beruf", bengali: "পেশা", example: "Was ist Ihr Beruf?" },
  { id: "a1-282", german: "der Arzt", bengali: "ডাক্তার (পুরুষ)", example: "Der Arzt ist freundlich." },
  { id: "a1-283", german: "die Ärztin", bengali: "ডাক্তার (মহিলা)", example: "Die Ärztin hilft mir." },
  { id: "a1-284", german: "der Lehrer", bengali: "শিক্ষক (পুরুষ)", example: "Der Lehrer erklärt gut." },
  { id: "a1-285", german: "die Lehrerin", bengali: "শিক্ষিকা", example: "Die Lehrerin ist nett." },
  { id: "a1-286", german: "der Koch", bengali: "রাঁধুনি", example: "Der Koch kocht sehr gut." },
  { id: "a1-287", german: "der Kellner", bengali: "ওয়েটার", example: "Der Kellner kommt gleich." },
  { id: "a1-288", german: "der Polizist", bengali: "পুলিশ", example: "Der Polizist hilft uns." },
  { id: "a1-289", german: "der Verkäufer", bengali: "বিক্রয়কর্মী", example: "Der Verkäufer ist freundlich." },
  { id: "a1-290", german: "der Ingenieur", bengali: "ইঞ্জিনিয়ার", example: "Der Ingenieur arbeitet viel." },
  { id: "a1-291", german: "der Student", bengali: "ছাত্র", example: "Der Student lernt viel." },
  { id: "a1-292", german: "die Studentin", bengali: "ছাত্রী", example: "Die Studentin ist fleißig." },
  { id: "a1-293", german: "der Fahrer", bengali: "চালক", example: "Der Fahrer fährt schnell." },
  { id: "a1-294", german: "der Bäcker", bengali: "রুটিওয়ালা", example: "Der Bäcker backt frisches Brot." },
  { id: "a1-295", german: "die Sekretärin", bengali: "সচিব", example: "Die Sekretärin organisiert alles." },
  { id: "a1-296", german: "der Anwalt", bengali: "আইনজীবী", example: "Der Anwalt hilft mir." },
  { id: "a1-297", german: "der Bauer", bengali: "কৃষক", example: "Der Bauer arbeitet auf dem Feld." },
  { id: "a1-298", german: "der Künstler", bengali: "শিল্পী", example: "Der Künstler malt ein Bild." },
  { id: "a1-299", german: "der Musiker", bengali: "সংগীতশিল্পী", example: "Der Musiker spielt Klavier." },
  { id: "a1-300", german: "arbeiten", bengali: "কাজ করা", example: "Ich arbeite viel." },

  // Sub-Level 16 — Tiere (301–320)
  { id: "a1-301", german: "das Tier", bengali: "প্রাণী", example: "Das Tier ist wild." },
  { id: "a1-302", german: "der Hund", bengali: "কুকুর", example: "Der Hund ist treu." },
  { id: "a1-303", german: "die Katze", bengali: "বিড়াল", example: "Die Katze schläft viel." },
  { id: "a1-304", german: "der Vogel", bengali: "পাখি", example: "Der Vogel singt schön." },
  { id: "a1-305", german: "der Fisch", bengali: "মাছ", example: "Der Fisch schwimmt schnell." },
  { id: "a1-306", german: "die Kuh", bengali: "গরু", example: "Die Kuh gibt Milch." },
  { id: "a1-307", german: "das Pferd", bengali: "ঘোড়া", example: "Das Pferd läuft schnell." },
  { id: "a1-308", german: "das Schaf", bengali: "ভেড়া", example: "Das Schaf ist weiß." },
  { id: "a1-309", german: "die Ziege", bengali: "ছাগল", example: "Die Ziege isst Gras." },
  { id: "a1-310", german: "das Schwein", bengali: "শূকর", example: "Das Schwein ist rosa." },
  { id: "a1-311", german: "das Huhn", bengali: "মুরগি", example: "Das Huhn legt Eier." },
  { id: "a1-312", german: "die Maus", bengali: "ইঁদুর", example: "Die Maus ist klein." },
  { id: "a1-313", german: "der Löwe", bengali: "সিংহ", example: "Der Löwe ist stark." },
  { id: "a1-314", german: "der Elefant", bengali: "হাতি", example: "Der Elefant ist groß." },
  { id: "a1-315", german: "der Affe", bengali: "বানর", example: "Der Affe klettert schnell." },
  { id: "a1-316", german: "die Schlange", bengali: "সাপ", example: "Die Schlange ist gefährlich." },
  { id: "a1-317", german: "der Schmetterling", bengali: "প্রজাপতি", example: "Der Schmetterling ist bunt." },
  { id: "a1-318", german: "die Spinne", bengali: "মাকড়সা", example: "Die Spinne hat acht Beine." },
  { id: "a1-319", german: "die Biene", bengali: "মৌমাছি", example: "Die Biene macht Honig." },
  { id: "a1-320", german: "füttern", bengali: "খাওয়ানো", example: "Ich füttere das Tier." },

  // Sub-Level 17 — Natur & Wetter (321–340)
  { id: "a1-321", german: "das Wetter", bengali: "আবহাওয়া", example: "Das Wetter ist schön." },
  { id: "a1-322", german: "die Sonne", bengali: "সূর্য", example: "Die Sonne scheint." },
  { id: "a1-323", german: "der Regen", bengali: "বৃষ্টি", example: "Der Regen ist stark." },
  { id: "a1-324", german: "der Schnee", bengali: "তুষার", example: "Der Schnee ist weiß." },
  { id: "a1-325", german: "der Wind", bengali: "বাতাস", example: "Der Wind ist stark." },
  { id: "a1-326", german: "die Wolke", bengali: "মেঘ", example: "Die Wolke ist grau." },
  { id: "a1-327", german: "heiß", bengali: "গরম", example: "Es ist sehr heiß." },
  { id: "a1-328", german: "kalt", bengali: "ঠান্ডা", example: "Es ist sehr kalt." },
  { id: "a1-329", german: "warm", bengali: "উষ্ণ", example: "Das Wetter ist warm." },
  { id: "a1-330", german: "windig", bengali: "বাতাসপূর্ণ", example: "Es ist sehr windig." },
  { id: "a1-331", german: "der Himmel", bengali: "আকাশ", example: "Der Himmel ist blau." },
  { id: "a1-332", german: "der Berg", bengali: "পাহাড়", example: "Der Berg ist hoch." },
  { id: "a1-333", german: "der See", bengali: "হ্রদ", example: "Der See ist ruhig." },
  { id: "a1-334", german: "das Meer", bengali: "সমুদ্র", example: "Das Meer ist blau." },
  { id: "a1-335", german: "der Wald", bengali: "বন", example: "Der Wald ist grün." },
  { id: "a1-336", german: "der Fluss", bengali: "নদী", example: "Der Fluss ist breit." },
  { id: "a1-337", german: "der Baum", bengali: "গাছ", example: "Der Baum ist groß." },
  { id: "a1-338", german: "die Blume", bengali: "ফুল", example: "Die Blume ist schön." },
  { id: "a1-339", german: "das Gras", bengali: "ঘাস", example: "Das Gras ist grün." },
  { id: "a1-340", german: "der Strand", bengali: "সমুদ্র সৈকত", example: "Der Strand ist schön." },

  // Sub-Level 18 — Schule & Lernen (341–360)
  { id: "a1-341", german: "die Schule", bengali: "স্কুল", example: "Die Schule beginnt um 8." },
  { id: "a1-342", german: "der Unterricht", bengali: "ক্লাস", example: "Der Unterricht beginnt um 8." },
  { id: "a1-343", german: "die Klasse", bengali: "শ্রেণি", example: "Die Klasse ist groß." },
  { id: "a1-344", german: "der Schüler", bengali: "ছাত্র (স্কুল)", example: "Der Schüler lernt viel." },
  { id: "a1-345", german: "das Buch", bengali: "বই", example: "Das Buch ist interessant." },
  { id: "a1-346", german: "das Heft", bengali: "খাতা", example: "Das Heft ist voll." },
  { id: "a1-347", german: "der Bleistift", bengali: "পেন্সিল", example: "Der Bleistift ist kurz." },
  { id: "a1-348", german: "der Kugelschreiber", bengali: "কলম", example: "Der Kugelschreiber ist blau." },
  { id: "a1-349", german: "die Tafel", bengali: "বোর্ড", example: "Schreiben Sie an die Tafel." },
  { id: "a1-350", german: "die Prüfung", bengali: "পরীক্ষা", example: "Die Prüfung ist morgen." },
  { id: "a1-351", german: "die Hausaufgabe", bengali: "বাড়ির কাজ", example: "Ich mache Hausaufgaben." },
  { id: "a1-352", german: "lernen", bengali: "শেখা", example: "Er lernt Deutsch." },
  { id: "a1-353", german: "schreiben", bengali: "লেখা", example: "Sie schreibt einen Brief." },
  { id: "a1-354", german: "lesen", bengali: "পড়া", example: "Er liest ein Buch." },
  { id: "a1-355", german: "verstehen", bengali: "বোঝা", example: "Ich verstehe das nicht." },
  { id: "a1-356", german: "fragen", bengali: "জিজ্ঞাসা করা", example: "Darf ich fragen?" },
  { id: "a1-357", german: "antworten", bengali: "উত্তর দেওয়া", example: "Ich antworte schnell." },
  { id: "a1-358", german: "die Note", bengali: "নম্বর/গ্রেড", example: "Meine Note ist gut." },
  { id: "a1-359", german: "das Wörterbuch", bengali: "অভিধান", example: "Das Wörterbuch ist nützlich." },
  { id: "a1-360", german: "der Kurs", bengali: "কোর্স", example: "Der Kurs beginnt um 9." },

  // Sub-Level 19 — Hobbys & Freizeit (361–380)
  { id: "a1-361", german: "das Hobby", bengali: "শখ", example: "Mein Hobby ist Lesen." },
  { id: "a1-362", german: "malen", bengali: "আঁকা", example: "Sie malt ein Bild." },
  { id: "a1-363", german: "singen", bengali: "গান গাওয়া", example: "Er singt ein Lied." },
  { id: "a1-364", german: "tanzen", bengali: "নাচা", example: "Sie tanzt sehr gut." },
  { id: "a1-365", german: "fotografieren", bengali: "ছবি তোলা", example: "Ich fotografiere gern." },
  { id: "a1-366", german: "reisen", bengali: "ভ্রমণ করা", example: "Ich reise gern." },
  { id: "a1-367", german: "die Musik", bengali: "সংগীত", example: "Musik macht glücklich." },
  { id: "a1-368", german: "der Film", bengali: "চলচ্চিত্র", example: "Der Film ist toll." },
  { id: "a1-369", german: "das Spiel", bengali: "খেলা", example: "Das Spiel macht Spaß." },
  { id: "a1-370", german: "spielen", bengali: "খেলা", example: "Die Kinder spielen draußen." },
  { id: "a1-371", german: "fernsehen", bengali: "টিভি দেখা", example: "Ich sehe abends fern." },
  { id: "a1-372", german: "die Party", bengali: "পার্টি", example: "Die Party ist toll." },
  { id: "a1-373", german: "feiern", bengali: "উদযাপন করা", example: "Wir feiern heute." },
  { id: "a1-374", german: "das Geschenk", bengali: "উপহার", example: "Das Geschenk ist schön." },
  { id: "a1-375", german: "einladen", bengali: "আমন্ত্রণ জানানো", example: "Ich lade dich ein." },
  { id: "a1-376", german: "besuchen", bengali: "দেখা করতে যাওয়া", example: "Ich besuche meine Freunde." },
  { id: "a1-377", german: "treffen", bengali: "দেখা করা", example: "Wir treffen uns um 5." },
  { id: "a1-378", german: "der Freund", bengali: "বন্ধু", example: "Mein Freund wohnt hier." },
  { id: "a1-379", german: "die Freundin", bengali: "বান্ধবী", example: "Meine Freundin lacht viel." },
  { id: "a1-380", german: "die Freizeit", bengali: "অবসর সময়", example: "Meine Freizeit ist kurz." },

  // Sub-Level 20 — Sport (381–400)
  { id: "a1-381", german: "der Sport", bengali: "খেলাধুলা", example: "Sport ist gesund." },
  { id: "a1-382", german: "der Fußball", bengali: "ফুটবল", example: "Fußball macht Spaß." },
  { id: "a1-383", german: "das Tennis", bengali: "টেনিস", example: "Tennis ist schwer." },
  { id: "a1-384", german: "das Schwimmen", bengali: "সাঁতার", example: "Schwimmen ist gesund." },
  { id: "a1-385", german: "das Laufen", bengali: "দৌড়ানো", example: "Laufen macht fit." },
  { id: "a1-386", german: "schwimmen", bengali: "সাঁতার কাটা", example: "Sie schwimmt sehr gut." },
  { id: "a1-387", german: "laufen", bengali: "দৌড়ানো", example: "Er läuft jeden Tag." },
  { id: "a1-388", german: "joggen", bengali: "জগিং করা", example: "Ich jogge jeden Morgen." },
  { id: "a1-389", german: "trainieren", bengali: "প্রশিক্ষণ নেওয়া", example: "Er trainiert täglich." },
  { id: "a1-390", german: "das Fitness-Studio", bengali: "জিম", example: "Ich gehe ins Fitness-Studio." },
  { id: "a1-391", german: "der Ball", bengali: "বল", example: "Der Ball ist rund." },
  { id: "a1-392", german: "das Spielfeld", bengali: "খেলার মাঠ", example: "Das Spielfeld ist groß." },
  { id: "a1-393", german: "die Mannschaft", bengali: "দল", example: "Die Mannschaft spielt gut." },
  { id: "a1-394", german: "gewinnen", bengali: "জেতা", example: "Wir gewinnen das Spiel." },
  { id: "a1-395", german: "verlieren", bengali: "হারা", example: "Sie verlieren das Spiel." },
  { id: "a1-396", german: "das Tor", bengali: "গোল", example: "Das Tor ist wichtig." },
  { id: "a1-397", german: "der Sieger", bengali: "বিজয়ী", example: "Der Sieger bekommt einen Preis." },
  { id: "a1-398", german: "der Trainer", bengali: "কোচ", example: "Der Trainer ist streng." },
  { id: "a1-399", german: "das Training", bengali: "অনুশীলন", example: "Das Training beginnt um 6." },
  { id: "a1-400", german: "fit", bengali: "সুস্থ/ফিট", example: "Er ist sehr fit." },

  // Sub-Level 21 — Gefühle & Emotionen (401–420)
  { id: "a1-401", german: "glücklich", bengali: "সুখী", example: "Ich bin sehr glücklich." },
  { id: "a1-402", german: "traurig", bengali: "দুঃখী", example: "Sie ist heute traurig." },
  { id: "a1-403", german: "müde", bengali: "ক্লান্ত", example: "Ich bin sehr müde." },
  { id: "a1-404", german: "hungrig", bengali: "ক্ষুধার্ত", example: "Ich bin sehr hungrig." },
  { id: "a1-405", german: "durstig", bengali: "তৃষ্ণার্ত", example: "Ich bin durstig." },
  { id: "a1-406", german: "wütend", bengali: "রাগান্বিত", example: "Er ist sehr wütend." },
  { id: "a1-407", german: "nervös", bengali: "নার্ভাস", example: "Er ist nervös vor der Prüfung." },
  { id: "a1-408", german: "überrascht", bengali: "বিস্মিত", example: "Ich bin total überrascht." },
  { id: "a1-409", german: "zufrieden", bengali: "সন্তুষ্ট", example: "Ich bin zufrieden." },
  { id: "a1-410", german: "einsam", bengali: "একাকী", example: "Er fühlt sich einsam." },
  { id: "a1-411", german: "stolz", bengali: "গর্বিত", example: "Ich bin stolz auf dich." },
  { id: "a1-412", german: "dankbar", bengali: "কৃতজ্ঞ", example: "Ich bin sehr dankbar." },
  { id: "a1-413", german: "gesund", bengali: "স্বাস্থ্যবান", example: "Ich bin wieder gesund." },
  { id: "a1-414", german: "krank", bengali: "অসুস্থ", example: "Ich bin krank." },
  { id: "a1-415", german: "entspannt", bengali: "শিথিল", example: "Ich bin heute entspannt." },
  { id: "a1-416", german: "gestresst", bengali: "চাপগ্রস্ত", example: "Ich bin sehr gestresst." },
  { id: "a1-417", german: "mögen", bengali: "পছন্দ করা", example: "Ich mag Schokolade." },
  { id: "a1-418", german: "lieben", bengali: "ভালোবাসা", example: "Ich liebe meine Familie." },
  { id: "a1-419", german: "lachen", bengali: "হাসা", example: "Sie lacht immer." },
  { id: "a1-420", german: "weinen", bengali: "কাঁদা", example: "Das Kind weint." },

  // Sub-Level 22 — Häufige Verben I (421–440)
  { id: "a1-421", german: "sein", bengali: "হওয়া", example: "Ich bin Student." },
  { id: "a1-422", german: "haben", bengali: "থাকা", example: "Ich habe ein Buch." },
  { id: "a1-423", german: "machen", bengali: "করা", example: "Was machst du?" },
  { id: "a1-424", german: "gehen", bengali: "যাওয়া", example: "Ich gehe in die Stadt." },
  { id: "a1-425", german: "kommen", bengali: "আসা", example: "Woher kommen Sie?" },
  { id: "a1-426", german: "sehen", bengali: "দেখা", example: "Ich sehe dich." },
  { id: "a1-427", german: "sagen", bengali: "বলা", example: "Was sagst du?" },
  { id: "a1-428", german: "wissen", bengali: "জানা", example: "Ich weiß das nicht." },
  { id: "a1-429", german: "geben", bengali: "দেওয়া", example: "Ich gebe dir das Buch." },
  { id: "a1-430", german: "nehmen", bengali: "নেওয়া", example: "Ich nehme das Ticket." },
  { id: "a1-431", german: "finden", bengali: "খুঁজে পাওয়া", example: "Ich finde das Hotel nicht." },
  { id: "a1-432", german: "denken", bengali: "ভাবা", example: "Ich denke viel." },
  { id: "a1-433", german: "wollen", bengali: "চাওয়া", example: "Ich will das nicht." },
  { id: "a1-434", german: "können", bengali: "পারা", example: "Ich kann Deutsch sprechen." },
  { id: "a1-435", german: "müssen", bengali: "করতেই হবে", example: "Ich muss jetzt gehen." },
  { id: "a1-436", german: "sollen", bengali: "উচিত", example: "Du sollst pünktlich sein." },
  { id: "a1-437", german: "dürfen", bengali: "অনুমতি থাকা", example: "Darf ich fragen?" },
  { id: "a1-438", german: "brauchen", bengali: "প্রয়োজন হওয়া", example: "Ich brauche Hilfe." },
  { id: "a1-439", german: "bleiben", bengali: "থাকা", example: "Ich bleibe zu Hause." },
  { id: "a1-440", german: "bringen", bengali: "আনা", example: "Ich bringe das Buch." },

  // Sub-Level 23 — Häufige Verben II (441–460)
  { id: "a1-441", german: "kaufen", bengali: "কেনা", example: "Er kauft ein Haus." },
  { id: "a1-442", german: "verkaufen", bengali: "বিক্রি করা", example: "Sie verkauft alles." },
  { id: "a1-443", german: "bezahlen", bengali: "পরিশোধ করা", example: "Ich bezahle die Rechnung." },
  { id: "a1-444", german: "kosten", bengali: "মূল্য হওয়া", example: "Was kostet das?" },
  { id: "a1-445", german: "öffnen", bengali: "খোলা", example: "Bitte öffnen Sie die Tür." },
  { id: "a1-446", german: "schließen", bengali: "বন্ধ করা", example: "Bitte schließen Sie die Tür." },
  { id: "a1-447", german: "warten", bengali: "অপেক্ষা করা", example: "Ich warte auf dich." },
  { id: "a1-448", german: "helfen", bengali: "সাহায্য করা", example: "Kann ich Ihnen helfen?" },
  { id: "a1-449", german: "zeigen", bengali: "দেখানো", example: "Zeigen Sie mir das." },
  { id: "a1-450", german: "suchen", bengali: "খোঁজা", example: "Ich suche den Bahnhof." },
  { id: "a1-451", german: "hören", bengali: "শোনা", example: "Ich höre Musik." },
  { id: "a1-452", german: "sprechen", bengali: "কথা বলা", example: "Ich spreche Deutsch." },
  { id: "a1-453", german: "erklären", bengali: "ব্যাখ্যা করা", example: "Er erklärt das Problem." },
  { id: "a1-454", german: "anrufen", bengali: "ফোন করা", example: "Ich rufe dich an." },
  { id: "a1-455", german: "schicken", bengali: "পাঠানো", example: "Ich schicke eine E-Mail." },
  { id: "a1-456", german: "beginnen", bengali: "শুরু করা", example: "Die Arbeit beginnt um 8." },
  { id: "a1-457", german: "beenden", bengali: "শেষ করা", example: "Ich beende die Arbeit." },
  { id: "a1-458", german: "vergessen", bengali: "ভুলে যাওয়া", example: "Ich vergesse oft." },
  { id: "a1-459", german: "erinnern", bengali: "মনে রাখা", example: "Ich erinnere mich." },
  { id: "a1-460", german: "versuchen", bengali: "চেষ্টা করা", example: "Ich versuche es." },

  // Sub-Level 24 — Häufige Verben III (461–480)
  { id: "a1-461", german: "anziehen", bengali: "পোশাক পরা", example: "Ich ziehe mich an." },
  { id: "a1-462", german: "ausziehen", bengali: "পোশাক খোলা", example: "Ich ziehe meine Jacke aus." },
  { id: "a1-463", german: "waschen", bengali: "ধোয়া", example: "Ich wasche die Wäsche." },
  { id: "a1-464", german: "putzen", bengali: "পরিষ্কার করা", example: "Ich putze das Haus." },
  { id: "a1-465", german: "aufräumen", bengali: "গোছানো", example: "Ich räume das Zimmer auf." },
  { id: "a1-466", german: "essen", bengali: "খাওয়া", example: "Ich esse gern Reis." },
  { id: "a1-467", german: "trinken", bengali: "পান করা", example: "Er trinkt Kaffee." },
  { id: "a1-468", german: "schlafen", bengali: "ঘুমানো", example: "Ich schlafe gut." },
  { id: "a1-469", german: "aufwachen", bengali: "জাগা", example: "Ich wache früh auf." },
  { id: "a1-470", german: "aufstehen", bengali: "উঠা", example: "Ich stehe um 6 auf." },
  { id: "a1-471", german: "duschen", bengali: "স্নান করা", example: "Ich dusche jeden Morgen." },
  { id: "a1-472", german: "fahren", bengali: "চালানো/যাওয়া", example: "Wir fahren nach Köln." },
  { id: "a1-473", german: "fliegen", bengali: "উড়া", example: "Wir fliegen nach Berlin." },
  { id: "a1-474", german: "reisen", bengali: "ভ্রমণ করা", example: "Ich reise gern." },
  { id: "a1-475", german: "wohnen", bengali: "বসবাস করা", example: "Ich wohne in Berlin." },
  { id: "a1-476", german: "leben", bengali: "জীবনযাপন করা", example: "Ich lebe gesund." },
  { id: "a1-477", german: "arbeiten", bengali: "কাজ করা", example: "Ich arbeite viel." },
  { id: "a1-478", german: "studieren", bengali: "পড়াশোনা করা", example: "Sie studiert Medizin." },
  { id: "a1-479", german: "spielen", bengali: "খেলা", example: "Die Kinder spielen draußen." },
  { id: "a1-480", german: "tanzen", bengali: "নাচা", example: "Sie tanzt sehr gut." },

  // Sub-Level 25 — Adjektive I (481–500)
  { id: "a1-481", german: "gut", bengali: "ভালো", example: "Das ist gut!" },
  { id: "a1-482", german: "schlecht", bengali: "খারাপ", example: "Das Wetter ist schlecht." },
  { id: "a1-483", german: "schön", bengali: "সুন্দর", example: "Das Wetter ist schön." },
  { id: "a1-484", german: "hässlich", bengali: "কুৎসিত", example: "Das Bild ist hässlich." },
  { id: "a1-485", german: "groß", bengali: "বড়", example: "Das Haus ist groß." },
  { id: "a1-486", german: "klein", bengali: "ছোট", example: "Das Kind ist klein." },
  { id: "a1-487", german: "lang", bengali: "লম্বা", example: "Die Straße ist lang." },
  { id: "a1-488", german: "kurz", bengali: "সংক্ষিপ্ত", example: "Der Rock ist kurz." },
  { id: "a1-489", german: "schnell", bengali: "দ্রুত", example: "Der Zug fährt schnell." },
  { id: "a1-490", german: "langsam", bengali: "ধীরে", example: "Bitte sprechen Sie langsam." },
  { id: "a1-491", german: "teuer", bengali: "দামি", example: "Das ist zu teuer." },
  { id: "a1-492", german: "billig", bengali: "সস্তা", example: "Das ist sehr billig." },
  { id: "a1-493", german: "leicht", bengali: "সহজ/হালকা", example: "Das ist sehr leicht." },
  { id: "a1-494", german: "schwer", bengali: "কঠিন/ভারী", example: "Deutsch ist schwer." },
  { id: "a1-495", german: "neu", bengali: "নতুন", example: "Das Auto ist neu." },
  { id: "a1-496", german: "alt", bengali: "পুরনো", example: "Das Buch ist alt." },
  { id: "a1-497", german: "jung", bengali: "তরুণ", example: "Er ist sehr jung." },
  { id: "a1-498", german: "stark", bengali: "শক্তিশালী", example: "Der Löwe ist stark." },
  { id: "a1-499", german: "schwach", bengali: "দুর্বল", example: "Nach der Krankheit war er schwach." },
  { id: "a1-500", german: "wichtig", bengali: "গুরুত্বপূর্ণ", example: "Das ist sehr wichtig." },

  // Sub-Level 26 — Adjektive II (501–520)
  { id: "a1-501", german: "einfach", bengali: "সহজ", example: "Das ist einfach!" },
  { id: "a1-502", german: "schwierig", bengali: "কঠিন", example: "Deutsch ist schwierig." },
  { id: "a1-503", german: "interessant", bengali: "আকর্ষণীয়", example: "Das Buch ist interessant." },
  { id: "a1-504", german: "langweilig", bengali: "বিরক্তিকর", example: "Der Film ist langweilig." },
  { id: "a1-505", german: "freundlich", bengali: "বন্ধুত্বপূর্ণ", example: "Er ist sehr freundlich." },
  { id: "a1-506", german: "höflich", bengali: "বিনয়ী", example: "Sie ist immer höflich." },
  { id: "a1-507", german: "nett", bengali: "ভালো/মিষ্টি", example: "Du bist sehr nett." },
  { id: "a1-508", german: "klug", bengali: "বুদ্ধিমান", example: "Das Kind ist klug." },
  { id: "a1-509", german: "lustig", bengali: "মজার", example: "Er ist sehr lustig." },
  { id: "a1-510", german: "ruhig", bengali: "শান্ত", example: "Das Baby ist ruhig." },
  { id: "a1-511", german: "laut", bengali: "শোরগোলপূর্ণ", example: "Die Straße ist laut." },
  { id: "a1-512", german: "sauber", bengali: "পরিষ্কার", example: "Das Zimmer ist sauber." },
  { id: "a1-513", german: "schmutzig", bengali: "নোংরা", example: "Die Hände sind schmutzig." },
  { id: "a1-514", german: "voll", bengali: "পূর্ণ", example: "Das Restaurant ist voll." },
  { id: "a1-515", german: "leer", bengali: "খালি", example: "Der Kühlschrank ist leer." },
  { id: "a1-516", german: "hell", bengali: "উজ্জ্বল", example: "Das Zimmer ist hell." },
  { id: "a1-517", german: "dunkel", bengali: "অন্ধকার", example: "Der Flur ist dunkel." },
  { id: "a1-518", german: "nah", bengali: "কাছাকাছি", example: "Der Bahnhof ist nah." },
  { id: "a1-519", german: "weit", bengali: "দূরে", example: "Das Hotel ist weit." },
  { id: "a1-520", german: "fertig", bengali: "সম্পন্ন", example: "Ich bin fertig." },

  // Sub-Level 27 — Präpositionen & Ortsangaben (521–540)
  { id: "a1-521", german: "in", bengali: "মধ্যে", example: "Ich wohne in Berlin." },
  { id: "a1-522", german: "auf", bengali: "উপরে", example: "Das Buch ist auf dem Tisch." },
  { id: "a1-523", german: "unter", bengali: "নিচে", example: "Die Katze ist unter dem Tisch." },
  { id: "a1-524", german: "neben", bengali: "পাশে", example: "Das Café ist neben der Bank." },
  { id: "a1-525", german: "zwischen", bengali: "মাঝে", example: "Das Kino ist zwischen zwei Cafés." },
  { id: "a1-526", german: "vor", bengali: "সামনে", example: "Das Auto steht vor dem Haus." },
  { id: "a1-527", german: "hinter", bengali: "পেছনে", example: "Der Park ist hinter dem Bahnhof." },
  { id: "a1-528", german: "über", bengali: "উপর দিয়ে", example: "Das Bild ist über dem Fernseher." },
  { id: "a1-529", german: "gegenüber", bengali: "বিপরীত দিকে", example: "Das Hotel ist gegenüber." },
  { id: "a1-530", german: "links", bengali: "বাম দিকে", example: "Gehen Sie links." },
  { id: "a1-531", german: "rechts", bengali: "ডান দিকে", example: "Biegen Sie rechts ab." },
  { id: "a1-532", german: "geradeaus", bengali: "সোজা", example: "Gehen Sie geradeaus." },
  { id: "a1-533", german: "hier", bengali: "এখানে", example: "Ich bin hier." },
  { id: "a1-534", german: "dort", bengali: "সেখানে", example: "Das Hotel ist dort." },
  { id: "a1-535", german: "oben", bengali: "উপরে", example: "Das Zimmer ist oben." },
  { id: "a1-536", german: "unten", bengali: "নিচে", example: "Die Küche ist unten." },
  { id: "a1-537", german: "drinnen", bengali: "ভেতরে", example: "Es ist drinnen warm." },
  { id: "a1-538", german: "draußen", bengali: "বাইরে", example: "Es ist draußen kalt." },
  { id: "a1-539", german: "überall", bengali: "সর্বত্র", example: "Touristen sind überall." },
  { id: "a1-540", german: "nirgendwo", bengali: "কোথাও না", example: "Ich finde es nirgendwo." },

  // Sub-Level 28 — Fragewörter & Konjunktionen (541–560)
  { id: "a1-541", german: "wer", bengali: "কে", example: "Wer ist das?" },
  { id: "a1-542", german: "was", bengali: "কি", example: "Was machst du?" },
  { id: "a1-543", german: "wo", bengali: "কোথায়", example: "Wo wohnst du?" },
  { id: "a1-544", german: "woher", bengali: "কোথা থেকে", example: "Woher kommst du?" },
  { id: "a1-545", german: "wohin", bengali: "কোথায় (গন্তব্য)", example: "Wohin gehst du?" },
  { id: "a1-546", german: "wann", bengali: "কখন", example: "Wann kommst du?" },
  { id: "a1-547", german: "wie", bengali: "কিভাবে", example: "Wie geht es dir?" },
  { id: "a1-548", german: "wie viel", bengali: "কত", example: "Wie viel kostet das?" },
  { id: "a1-549", german: "wie viele", bengali: "কতগুলো", example: "Wie viele Personen sind das?" },
  { id: "a1-550", german: "warum", bengali: "কেন", example: "Warum lernst du Deutsch?" },
  { id: "a1-551", german: "welche", bengali: "কোনটি", example: "Welche Größe haben Sie?" },
  { id: "a1-552", german: "und", bengali: "এবং", example: "Ich und du." },
  { id: "a1-553", german: "oder", bengali: "অথবা", example: "Tee oder Kaffee?" },
  { id: "a1-554", german: "aber", bengali: "কিন্তু", example: "Ich möchte, aber ich kann nicht." },
  { id: "a1-555", german: "denn", bengali: "কারণ", example: "Ich lerne Deutsch, denn es macht Spaß." },
  { id: "a1-556", german: "weil", bengali: "কারণ", example: "Ich bleibe zu Hause, weil ich krank bin." },
  { id: "a1-557", german: "wenn", bengali: "যদি/যখন", example: "Wenn es regnet, bleibe ich zu Hause." },
  { id: "a1-558", german: "dass", bengali: "যে", example: "Ich glaube, dass es regnet." },
  { id: "a1-559", german: "obwohl", bengali: "যদিও", example: "Ich gehe, obwohl es regnet." },
  { id: "a1-560", german: "deshalb", bengali: "তাই", example: "Es regnet, deshalb bleibe ich zu Hause." },

  // Sub-Level 29 — Zeit-Adverbien (561–580)
  { id: "a1-561", german: "bald", bengali: "শীঘ্রই", example: "Ich komme bald." },
  { id: "a1-562", german: "schon", bengali: "ইতিমধ্যে", example: "Ich bin schon fertig." },
  { id: "a1-563", german: "noch", bengali: "এখনো", example: "Ich lerne noch Deutsch." },
  { id: "a1-564", german: "gleich", bengali: "এখনই", example: "Ich komme gleich." },
  { id: "a1-565", german: "später", bengali: "পরে", example: "Ich rufe später an." },
  { id: "a1-566", german: "vorher", bengali: "আগে", example: "Ich esse vorher." },
  { id: "a1-567", german: "danach", bengali: "তারপর", example: "Danach gehe ich schlafen." },
  { id: "a1-568", german: "zuerst", bengali: "প্রথমে", example: "Zuerst frühstücke ich." },
  { id: "a1-569", german: "dann", bengali: "তারপর", example: "Dann fahre ich zur Arbeit." },
  { id: "a1-570", german: "endlich", bengali: "শেষপর্যন্ত", example: "Endlich bin ich fertig!" },
  { id: "a1-571", german: "plötzlich", bengali: "আকস্মিকভাবে", example: "Plötzlich fängt es an zu regnen." },
  { id: "a1-572", german: "meistens", bengali: "প্রায়শই", example: "Ich esse meistens zu Hause." },
  { id: "a1-573", german: "täglich", bengali: "প্রতিদিন", example: "Ich lerne täglich Deutsch." },
  { id: "a1-574", german: "wöchentlich", bengali: "সাপ্তাহিক", example: "Ich gehe wöchentlich einkaufen." },
  { id: "a1-575", german: "monatlich", bengali: "মাসিক", example: "Die Miete ist monatlich." },
  { id: "a1-576", german: "jährlich", bengali: "বার্ষিক", example: "Wir reisen jährlich." },
  { id: "a1-577", german: "einmal", bengali: "একবার", example: "Ich war einmal in Berlin." },
  { id: "a1-578", german: "zweimal", bengali: "দুইবার", example: "Ich nehme die Tablette zweimal." },
  { id: "a1-579", german: "nochmal", bengali: "আরেকবার", example: "Sagen Sie das bitte nochmal." },
  { id: "a1-580", german: "sofort", bengali: "এখনই", example: "Komm jetzt sofort!" },

  // Sub-Level 30 — Einkaufen & Geld (581–600)
  { id: "a1-581", german: "das Geld", bengali: "টাকা", example: "Ich habe kein Geld." },
  { id: "a1-582", german: "der Preis", bengali: "দাম", example: "Der Preis ist hoch." },
  { id: "a1-583", german: "die Rechnung", bengali: "বিল", example: "Die Rechnung bitte!" },
  { id: "a1-584", german: "die Quittung", bengali: "রসিদ", example: "Haben Sie die Quittung?" },
  { id: "a1-585", german: "der Rabatt", bengali: "ছাড়", example: "Der Rabatt ist groß." },
  { id: "a1-586", german: "das Angebot", bengali: "অফার", example: "Das Angebot ist gut." },
  { id: "a1-587", german: "das Geschäft", bengali: "দোকান", example: "Das Geschäft ist offen." },
  { id: "a1-588", german: "der Markt", bengali: "বাজার", example: "Der Markt ist voll." },
  { id: "a1-589", german: "die Kasse", bengali: "ক্যাশ কাউন্টার", example: "Die Kasse ist dort." },
  { id: "a1-590", german: "bezahlen", bengali: "পরিশোধ করা", example: "Ich bezahle die Rechnung." },
  { id: "a1-591", german: "bar bezahlen", bengali: "নগদে পরিশোধ করা", example: "Ich bezahle bar." },
  { id: "a1-592", german: "die Kreditkarte", bengali: "ক্রেডিট কার্ড", example: "Die Kreditkarte ist praktisch." },
  { id: "a1-593", german: "umtauschen", bengali: "বদলানো", example: "Ich möchte das umtauschen." },
  { id: "a1-594", german: "anprobieren", bengali: "পরে দেখা", example: "Ich probiere die Jacke an." },
  { id: "a1-595", german: "passen", bengali: "ফিট হওয়া", example: "Die Hose passt gut." },
  { id: "a1-596", german: "die Größe", bengali: "সাইজ", example: "Welche Größe haben Sie?" },
  { id: "a1-597", german: "zu groß", bengali: "খুব বড়", example: "Das ist zu groß." },
  { id: "a1-598", german: "zu klein", bengali: "খুব ছোট", example: "Das ist zu klein." },
  { id: "a1-599", german: "zu teuer", bengali: "খুব দামি", example: "Das ist zu teuer." },
  { id: "a1-600", german: "kostenlos", bengali: "বিনামূল্যে", example: "Das ist kostenlos." },

  // Sub-Level 31 — Technologie & Kommunikation (601–620)
  { id: "a1-601", german: "das Handy", bengali: "মোবাইল ফোন", example: "Mein Handy ist neu." },
  { id: "a1-602", german: "das Telefon", bengali: "টেলিফোন", example: "Das Telefon klingelt." },
  { id: "a1-603", german: "der Computer", bengali: "কম্পিউটার", example: "Der Computer ist neu." },
  { id: "a1-604", german: "das Internet", bengali: "ইন্টারনেট", example: "Das Internet ist schnell." },
  { id: "a1-605", german: "die E-Mail", bengali: "ইমেইল", example: "Ich schreibe eine E-Mail." },
  { id: "a1-606", german: "die Nachricht", bengali: "বার্তা", example: "Ich schicke eine Nachricht." },
  { id: "a1-607", german: "der Anruf", bengali: "ফোন কল", example: "Der Anruf war kurz." },
  { id: "a1-608", german: "die App", bengali: "অ্যাপ", example: "Die App ist kostenlos." },
  { id: "a1-609", german: "das Passwort", bengali: "পাসওয়ার্ড", example: "Das Passwort ist sicher." },
  { id: "a1-610", german: "die Webseite", bengali: "ওয়েবসাইট", example: "Die Webseite ist neu." },
  { id: "a1-611", german: "herunterladen", bengali: "ডাউনলোড করা", example: "Ich lade die App herunter." },
  { id: "a1-612", german: "hochladen", bengali: "আপলোড করা", example: "Ich lade das Foto hoch." },
  { id: "a1-613", german: "klicken", bengali: "ক্লিক করা", example: "Klicken Sie hier." },
  { id: "a1-614", german: "speichern", bengali: "সংরক্ষণ করা", example: "Ich speichere die Datei." },
  { id: "a1-615", german: "drucken", bengali: "প্রিন্ট করা", example: "Ich drucke das Dokument." },
  { id: "a1-616", german: "das Foto", bengali: "ছবি", example: "Das Foto ist schön." },
  { id: "a1-617", german: "das Video", bengali: "ভিডিও", example: "Das Video ist lang." },
  { id: "a1-618", german: "der Drucker", bengali: "প্রিন্টার", example: "Der Drucker ist kaputt." },
  { id: "a1-619", german: "das WLAN", bengali: "ওয়াইফাই", example: "Ich habe kein WLAN." },
  { id: "a1-620", german: "die Verbindung", bengali: "সংযোগ", example: "Die Verbindung ist schlecht." },

  // Sub-Level 32 — Gesundheit & Arzt (621–640)
  { id: "a1-621", german: "die Gesundheit", bengali: "স্বাস্থ্য", example: "Gesundheit ist wichtig." },
  { id: "a1-622", german: "krank", bengali: "অসুস্থ", example: "Ich bin krank." },
  { id: "a1-623", german: "das Fieber", bengali: "জ্বর", example: "Ich habe Fieber." },
  { id: "a1-624", german: "der Husten", bengali: "কাশি", example: "Mein Husten ist schlimm." },
  { id: "a1-625", german: "der Schnupfen", bengali: "সর্দি", example: "Ich habe Schnupfen." },
  { id: "a1-626", german: "der Schmerz", bengali: "ব্যথা", example: "Der Schmerz ist stark." },
  { id: "a1-627", german: "wehtun", bengali: "ব্যথা করা", example: "Mein Kopf tut weh." },
  { id: "a1-628", german: "das Medikament", bengali: "ওষুধ", example: "Das Medikament hilft." },
  { id: "a1-629", german: "die Tablette", bengali: "ট্যাবলেট", example: "Ich nehme eine Tablette." },
  { id: "a1-630", german: "das Rezept", bengali: "প্রেসক্রিপশন", example: "Der Arzt gibt ein Rezept." },
  { id: "a1-631", german: "die Apotheke", bengali: "ওষুধের দোকান", example: "Die Apotheke ist offen." },
  { id: "a1-632", german: "der Arzt", bengali: "ডাক্তার", example: "Ich habe einen Termin beim Arzt." },
  { id: "a1-633", german: "das Krankenhaus", bengali: "হাসপাতাল", example: "Das Krankenhaus ist groß." },
  { id: "a1-634", german: "die Untersuchung", bengali: "পরীক্ষা", example: "Die Untersuchung ist wichtig." },
  { id: "a1-635", german: "gesund", bengali: "স্বাস্থ্যবান", example: "Ich bin wieder gesund." },
  { id: "a1-636", german: "sich erholen", bengali: "সুস্থ হওয়া", example: "Ich erhole mich schnell." },
  { id: "a1-637", german: "der Termin", bengali: "অ্যাপয়েন্টমেন্ট", example: "Ich habe einen Termin." },
  { id: "a1-638", german: "die Versicherung", bengali: "বীমা", example: "Die Versicherung ist wichtig." },
  { id: "a1-639", german: "der Notfall", bengali: "জরুরি অবস্থা", example: "Das ist ein Notfall!" },
  { id: "a1-640", german: "die Erste Hilfe", bengali: "প্রাথমিক চিকিৎসা", example: "Erste Hilfe ist wichtig." },

  // Sub-Level 33 — Reisen & Urlaub (641–660)
  { id: "a1-641", german: "die Reise", bengali: "ভ্রমণ", example: "Die Reise war schön." },
  { id: "a1-642", german: "der Urlaub", bengali: "ছুটি", example: "Ich fahre in Urlaub." },
  { id: "a1-643", german: "der Koffer", bengali: "সুটকেস", example: "Der Koffer ist schwer." },
  { id: "a1-644", german: "der Rucksack", bengali: "ব্যাকপ্যাক", example: "Der Rucksack ist leicht." },
  { id: "a1-645", german: "der Pass", bengali: "পাসপোর্ট", example: "Mein Pass ist neu." },
  { id: "a1-646", german: "das Visum", bengali: "ভিসা", example: "Das Visum ist fertig." },
  { id: "a1-647", german: "die Buchung", bengali: "বুকিং", example: "Die Buchung ist fertig." },
  { id: "a1-648", german: "buchen", bengali: "বুক করা", example: "Ich buche ein Hotel." },
  { id: "a1-649", german: "das Hotel", bengali: "হোটেল", example: "Das Hotel ist teuer." },
  { id: "a1-650", german: "die Unterkunft", bengali: "থাকার জায়গা", example: "Die Unterkunft ist gut." },
  { id: "a1-651", german: "die Sehenswürdigkeit", bengali: "দর্শনীয় স্থান", example: "Die Sehenswürdigkeit ist bekannt." },
  { id: "a1-652", german: "der Strand", bengali: "সমুদ্র সৈকত", example: "Der Strand ist schön." },
  { id: "a1-653", german: "die Landschaft", bengali: "প্রাকৃতিক দৃশ্য", example: "Die Landschaft ist wunderschön." },
  { id: "a1-654", german: "fotografieren", bengali: "ছবি তোলা", example: "Ich fotografiere viel." },
  { id: "a1-655", german: "ankommen", bengali: "পৌঁছানো", example: "Wir kommen morgen an." },
  { id: "a1-656", german: "abreisen", bengali: "প্রস্থান করা", example: "Die Abreise ist morgen." },
  { id: "a1-657", german: "das Souvenir", bengali: "স্মারক", example: "Das Souvenir ist schön." },
  { id: "a1-658", german: "die Postkarte", bengali: "পোস্টকার্ড", example: "Ich schreibe eine Postkarte." },
  { id: "a1-659", german: "das Gepäck", bengali: "মালপত্র", example: "Das Gepäck ist schwer." },
  { id: "a1-660", german: "die Grenze", bengali: "সীমান্ত", example: "Die Grenze ist offen." },

  // Sub-Level 34 — Wohnen & Alltag (661–680)
  { id: "a1-661", german: "der Alltag", bengali: "প্রতিদিনের জীবন", example: "Der Alltag ist manchmal stressig." },
  { id: "a1-662", german: "aufstehen", bengali: "উঠা", example: "Ich stehe um 6 auf." },
  { id: "a1-663", german: "frühstücken", bengali: "সকালের নাস্তা করা", example: "Ich frühstücke um 7." },
  { id: "a1-664", german: "zur Arbeit gehen", bengali: "কাজে যাওয়া", example: "Ich gehe zur Arbeit." },
  { id: "a1-665", german: "einkaufen", bengali: "কেনাকাটা করা", example: "Ich kaufe heute ein." },
  { id: "a1-666", german: "putzen", bengali: "পরিষ্কার করা", example: "Ich putze das Haus." },
  { id: "a1-667", german: "die Wäsche waschen", bengali: "কাপড় ধোয়া", example: "Ich wasche die Wäsche." },
  { id: "a1-668", german: "kochen", bengali: "রান্না করা", example: "Wer kocht heute?" },
  { id: "a1-669", german: "fernsehen", bengali: "টিভি দেখা", example: "Ich sehe abends fern." },
  { id: "a1-670", german: "schlafen gehen", bengali: "ঘুমাতে যাওয়া", example: "Ich gehe um 10 schlafen." },
  { id: "a1-671", german: "die Nachbarn", bengali: "প্রতিবেশীরা", example: "Meine Nachbarn sind freundlich." },
  { id: "a1-672", german: "die Miete", bengali: "ভাড়া", example: "Die Miete ist hoch." },
  { id: "a1-673", german: "der Vermieter", bengali: "বাড়িওয়ালা", example: "Der Vermieter ist nett." },
  { id: "a1-674", german: "umziehen", bengali: "স্থানান্তরিত হওয়া", example: "Ich ziehe nächsten Monat um." },
  { id: "a1-675", german: "renovieren", bengali: "সংস্কার করা", example: "Wir renovieren die Wohnung." },
  { id: "a1-676", german: "die Pflanze", bengali: "গাছ (ঘরে রাখার)", example: "Die Pflanze ist grün." },
  { id: "a1-677", german: "der Müll", bengali: "বর্জ্য", example: "Der Müll ist voll." },
  { id: "a1-678", german: "der Nachbar", bengali: "প্রতিবেশী", example: "Mein Nachbar ist freundlich." },
  { id: "a1-679", german: "ruhig", bengali: "শান্ত", example: "Das Schlafzimmer ist ruhig." },
  { id: "a1-680", german: "gemütlich", bengali: "আরামদায়ক", example: "Das Wohnzimmer ist gemütlich." },

  // Sub-Level 35 — Restaurant & Café (681–700)
  { id: "a1-681", german: "das Restaurant", bengali: "রেস্তোরাঁ", example: "Das Restaurant ist voll." },
  { id: "a1-682", german: "die Speisekarte", bengali: "মেনু", example: "Die Speisekarte ist groß." },
  { id: "a1-683", german: "bestellen", bengali: "অর্ডার করা", example: "Ich bestelle eine Suppe." },
  { id: "a1-684", german: "der Kellner", bengali: "ওয়েটার", example: "Der Kellner kommt gleich." },
  { id: "a1-685", german: "die Vorspeise", bengali: "স্টার্টার", example: "Die Vorspeise ist lecker." },
  { id: "a1-686", german: "das Hauptgericht", bengali: "মূল খাবার", example: "Das Hauptgericht ist groß." },
  { id: "a1-687", german: "die Nachspeise", bengali: "ডেজার্ট", example: "Die Nachspeise ist süß." },
  { id: "a1-688", german: "das Trinkgeld", bengali: "বকশিশ", example: "Das Trinkgeld ist nett." },
  { id: "a1-689", german: "lecker", bengali: "সুস্বাদু", example: "Das Essen ist lecker." },
  { id: "a1-690", german: "satt", bengali: "পেট ভরা", example: "Ich bin satt." },
  { id: "a1-691", german: "hungrig", bengali: "ক্ষুধার্ত", example: "Ich bin sehr hungrig." },
  { id: "a1-692", german: "reservieren", bengali: "রিজার্ভ করা", example: "Ich reserviere einen Tisch." },
  { id: "a1-693", german: "das Café", bengali: "ক্যাফে", example: "Das Café ist gemütlich." },
  { id: "a1-694", german: "der Kaffee", bengali: "কফি", example: "Der Kaffee ist stark." },
  { id: "a1-695", german: "der Tee", bengali: "চা", example: "Der Tee ist heiß." },
  { id: "a1-696", german: "das Gericht", bengali: "খাবারের পদ", example: "Das Gericht ist frisch." },
  { id: "a1-697", german: "vegetarisch", bengali: "নিরামিষ", example: "Das Gericht ist vegetarisch." },
  { id: "a1-698", german: "die Allergie", bengali: "অ্যালার্জি", example: "Ich habe eine Allergie." },
  { id: "a1-699", german: "die Rechnung", bengali: "বিল", example: "Die Rechnung bitte!" },
  { id: "a1-700", german: "getrennt zahlen", bengali: "আলাদা করে পরিশোধ করা", example: "Wir möchten getrennt zahlen." },

  // Sub-Level 36 — Arbeit & Büro (701–720)
  { id: "a1-701", german: "die Arbeit", bengali: "কাজ", example: "Die Arbeit macht Spaß." },
  { id: "a1-702", german: "das Büro", bengali: "অফিস", example: "Das Büro ist groß." },
  { id: "a1-703", german: "der Chef", bengali: "বস", example: "Mein Chef ist nett." },
  { id: "a1-704", german: "der Kollege", bengali: "সহকর্মী", example: "Mein Kollege heißt Tom." },
  { id: "a1-705", german: "die Besprechung", bengali: "মিটিং", example: "Die Besprechung beginnt um 9." },
  { id: "a1-706", german: "der Termin", bengali: "অ্যাপয়েন্টমেন্ট", example: "Ich habe einen Termin." },
  { id: "a1-707", german: "das Projekt", bengali: "প্রজেক্ট", example: "Das Projekt läuft gut." },
  { id: "a1-708", german: "die Pause", bengali: "বিরতি", example: "Ich mache eine Pause." },
  { id: "a1-709", german: "pünktlich", bengali: "সময়মতো", example: "Er ist immer pünktlich." },
  { id: "a1-710", german: "der Feierabend", bengali: "কাজ শেষের সময়", example: "Endlich Feierabend!" },
  { id: "a1-711", german: "das Gehalt", bengali: "বেতন", example: "Das Gehalt ist gut." },
  { id: "a1-712", german: "der Urlaub", bengali: "ছুটি", example: "Ich nehme Urlaub." },
  { id: "a1-713", german: "krank", bengali: "অসুস্থ", example: "Ich bin heute krank." },
  { id: "a1-714", german: "fleißig", bengali: "পরিশ্রমী", example: "Sie ist sehr fleißig." },
  { id: "a1-715", german: "müde", bengali: "ক্লান্ত", example: "Ich bin sehr müde." },
  { id: "a1-716", german: "wichtig", bengali: "গুরুত্বপূর্ণ", example: "Das ist sehr wichtig." },
  { id: "a1-717", german: "die Aufgabe", bengali: "কাজ/দায়িত্ব", example: "Die Aufgabe ist schwer." },
  { id: "a1-718", german: "der Computer", bengali: "কম্পিউটার", example: "Der Computer ist neu." },
  { id: "a1-719", german: "das Dokument", bengali: "দলিল", example: "Das Dokument ist fertig." },
  { id: "a1-720", german: "die E-Mail", bengali: "ইমেইল", example: "Ich schreibe eine E-Mail." },

  // Sub-Level 37 — Bildung & Universität (721–740)
  { id: "a1-721", german: "die Universität", bengali: "বিশ্ববিদ্যালয়", example: "Die Universität ist groß." },
  { id: "a1-722", german: "das Studium", bengali: "উচ্চশিক্ষা", example: "Das Studium ist schwer." },
  { id: "a1-723", german: "der Professor", bengali: "অধ্যাপক", example: "Der Professor erklärt gut." },
  { id: "a1-724", german: "die Vorlesung", bengali: "বক্তৃতা", example: "Die Vorlesung beginnt um 10." },
  { id: "a1-725", german: "das Seminar", bengali: "সেমিনার", example: "Das Seminar ist interessant." },
  { id: "a1-726", german: "die Prüfung", bengali: "পরীক্ষা", example: "Die Prüfung ist morgen." },
  { id: "a1-727", german: "die Note", bengali: "গ্রেড", example: "Meine Note ist gut." },
  { id: "a1-728", german: "das Zeugnis", bengali: "সার্টিফিকেট", example: "Das Zeugnis ist fertig." },
  { id: "a1-729", german: "der Abschluss", bengali: "ডিগ্রি", example: "Mein Abschluss ist gut." },
  { id: "a1-730", german: "das Praktikum", bengali: "ইন্টার্নশিপ", example: "Das Praktikum macht Spaß." },
  { id: "a1-731", german: "die Bibliothek", bengali: "গ্রন্থাগার", example: "Die Bibliothek ist ruhig." },
  { id: "a1-732", german: "die Bewerbung", bengali: "আবেদন", example: "Meine Bewerbung ist fertig." },
  { id: "a1-733", german: "der Lebenslauf", bengali: "জীবনবৃত্তান্ত", example: "Mein Lebenslauf ist fertig." },
  { id: "a1-734", german: "das Stipendium", bengali: "বৃত্তি", example: "Das Stipendium hilft mir." },
  { id: "a1-735", german: "die Fakultät", bengali: "অনুষদ", example: "Die Fakultät ist groß." },
  { id: "a1-736", german: "das Fach", bengali: "বিষয়", example: "Mein Fach ist Medizin." },
  { id: "a1-737", german: "die Klausur", bengali: "লিখিত পরীক্ষা", example: "Die Klausur ist schwer." },
  { id: "a1-738", german: "studieren", bengali: "পড়াশোনা করা", example: "Sie studiert Medizin." },
  { id: "a1-739", german: "unterrichten", bengali: "শিক্ষা দেওয়া", example: "Er unterrichtet Deutsch." },
  { id: "a1-740", german: "lehren", bengali: "শিক্ষা দেওয়া", example: "Sie lehrt an der Uni." },

  // Sub-Level 38 — Wetter & Jahreszeiten (741–760)
  { id: "a1-741", german: "der Frühling", bengali: "বসন্ত", example: "Im Frühling blühen die Blumen." },
  { id: "a1-742", german: "der Sommer", bengali: "গ্রীষ্ম", example: "Der Sommer ist heiß." },
  { id: "a1-743", german: "der Herbst", bengali: "শরৎ", example: "Der Herbst ist windig." },
  { id: "a1-744", german: "der Winter", bengali: "শীত", example: "Der Winter ist kalt." },
  { id: "a1-745", german: "die Jahreszeit", bengali: "ঋতু", example: "Welche Jahreszeit magst du?" },
  { id: "a1-746", german: "sonnig", bengali: "রোদেলা", example: "Es ist ein sonniger Tag." },
  { id: "a1-747", german: "bewölkt", bengali: "মেঘলা", example: "Der Himmel ist bewölkt." },
  { id: "a1-748", german: "regnerisch", bengali: "বৃষ্টিময়", example: "Das Wetter ist regnerisch." },
  { id: "a1-749", german: "schneien", bengali: "তুষারপাত হওয়া", example: "Es schneit draußen." },
  { id: "a1-750", german: "regnen", bengali: "বৃষ্টি হওয়া", example: "Es regnet stark." },
  { id: "a1-751", german: "der Grad", bengali: "ডিগ্রি", example: "Es sind dreißig Grad." },
  { id: "a1-752", german: "die Temperatur", bengali: "তাপমাত্রা", example: "Die Temperatur ist hoch." },
  { id: "a1-753", german: "das Gewitter", bengali: "বজ্রঝড়", example: "Das Gewitter ist laut." },
  { id: "a1-754", german: "der Nebel", bengali: "কুয়াশা", example: "Der Nebel ist dicht." },
  { id: "a1-755", german: "das Eis", bengali: "বরফ", example: "Das Eis ist glatt." },
  { id: "a1-756", german: "der Frost", bengali: "হিম", example: "Der Frost ist gefährlich." },
  { id: "a1-757", german: "die Hitze", bengali: "তীব্র গরম", example: "Die Hitze ist unerträglich." },
  { id: "a1-758", german: "die Kälte", bengali: "তীব্র ঠান্ডা", example: "Die Kälte ist stark." },
  { id: "a1-759", german: "der Regenschirm", bengali: "ছাতা", example: "Ich brauche einen Regenschirm." },
  { id: "a1-760", german: "die Sonnenbrille", bengali: "সানগ্লাস", example: "Meine Sonnenbrille ist neu." },

  // Sub-Level 39 — Haustiere & weitere Tiere (761–780)
  { id: "a1-761", german: "das Haustier", bengali: "পালিত প্রাণী", example: "Mein Haustier ist ein Hund." },
  { id: "a1-762", german: "der Hamster", bengali: "হ্যামস্টার", example: "Der Hamster ist klein." },
  { id: "a1-763", german: "das Kaninchen", bengali: "খরগোশ (পালিত)", example: "Das Kaninchen ist weiß." },
  { id: "a1-764", german: "der Papagei", bengali: "টিয়াপাখি", example: "Der Papagei spricht." },
  { id: "a1-765", german: "der Frosch", bengali: "কোলাব্যাঙ", example: "Der Frosch ist grün." },
  { id: "a1-766", german: "die Ente", bengali: "হাঁস", example: "Die Ente schwimmt." },
  { id: "a1-767", german: "die Gans", bengali: "রাজহাঁস", example: "Die Gans ist groß." },
  { id: "a1-768", german: "der Bär", bengali: "ভাল্লুক", example: "Der Bär ist stark." },
  { id: "a1-769", german: "der Wolf", bengali: "নেকড়ে", example: "Der Wolf ist wild." },
  { id: "a1-770", german: "der Fuchs", bengali: "শিয়াল", example: "Der Fuchs ist schlau." },
  { id: "a1-771", german: "das Kamel", bengali: "উট", example: "Das Kamel lebt in der Wüste." },
  { id: "a1-772", german: "der Tiger", bengali: "বাঘ", example: "Der Tiger ist gefährlich." },
  { id: "a1-773", german: "die Giraffe", bengali: "জিরাফ", example: "Die Giraffe ist sehr groß." },
  { id: "a1-774", german: "das Krokodil", bengali: "কুমির", example: "Das Krokodil lebt im Fluss." },
  { id: "a1-775", german: "die Schildkröte", bengali: "কচ্ছপ", example: "Die Schildkröte ist langsam." },
  { id: "a1-776", german: "der Hase", bengali: "খরগোশ", example: "Der Hase läuft schnell." },
  { id: "a1-777", german: "das Insekt", bengali: "পোকা", example: "Das Insekt ist klein." },
  { id: "a1-778", german: "die Fliege", bengali: "মাছি", example: "Die Fliege ist lästig." },
  { id: "a1-779", german: "die Ameise", bengali: "পিঁপড়া", example: "Die Ameise ist fleißig." },
  { id: "a1-780", german: "der Vogel", bengali: "পাখি", example: "Der Vogel fliegt hoch." },

  // Sub-Level 40 — Möbel & Haushalt II (781–800)
  { id: "a1-781", german: "der Vorhang", bengali: "পর্দা", example: "Der Vorhang ist lang." },
  { id: "a1-782", german: "die Decke", bengali: "ছাদ/কম্বল", example: "Die Decke ist warm." },
  { id: "a1-783", german: "das Kissen", bengali: "বালিশ/কুশন", example: "Das Kissen ist weich." },
  { id: "a1-784", german: "die Matratze", bengali: "গদি", example: "Die Matratze ist neu." },
  { id: "a1-785", german: "der Wecker", bengali: "এলার্ম ক্লক", example: "Der Wecker klingelt um 6." },
  { id: "a1-786", german: "die Steckdose", bengali: "সকেট", example: "Die Steckdose ist kaputt." },
  { id: "a1-787", german: "die Glühbirne", bengali: "বাতির বাল্ব", example: "Die Glühbirne ist hell." },
  { id: "a1-788", german: "der Staubsauger", bengali: "ভ্যাকুয়াম ক্লিনার", example: "Der Staubsauger ist laut." },
  { id: "a1-789", german: "der Besen", bengali: "ঝাড়ু", example: "Der Besen ist alt." },
  { id: "a1-790", german: "der Eimer", bengali: "বালতি", example: "Der Eimer ist voll." },
  { id: "a1-791", german: "die Treppe", bengali: "সিঁড়ি", example: "Die Treppe ist steil." },
  { id: "a1-792", german: "der Aufzug", bengali: "লিফট", example: "Der Aufzug ist kaputt." },
  { id: "a1-793", german: "der Schlüssel", bengali: "চাবি", example: "Der Schlüssel ist verloren." },
  { id: "a1-794", german: "das Schloss", bengali: "তালা", example: "Das Schloss ist neu." },
  { id: "a1-795", german: "die Klingel", bengali: "বেল", example: "Die Klingel funktioniert nicht." },
  { id: "a1-796", german: "der Briefkasten", bengali: "ডাকবাক্স", example: "Der Briefkasten ist voll." },
  { id: "a1-797", german: "die Garage", bengali: "গ্যারেজ", example: "Die Garage ist groß." },
  { id: "a1-798", german: "der Keller", bengali: "বেসমেন্ট", example: "Der Keller ist dunkel." },
  { id: "a1-799", german: "das Dach", bengali: "ছাদ (বাড়ির)", example: "Das Dach ist neu." },
  { id: "a1-800", german: "die Wand", bengali: "দেয়াল", example: "Die Wand ist weiß." },

  // Sub-Level 41 — Persönliche Daten & Dokumente (801–820)
  { id: "a1-801", german: "der Name", bengali: "নাম", example: "Mein Name ist Zishan." },
  { id: "a1-802", german: "der Vorname", bengali: "প্রথম নাম", example: "Mein Vorname ist Zishan." },
  { id: "a1-803", german: "der Nachname", bengali: "পারিবারিক নাম", example: "Wie ist Ihr Nachname?" },
  { id: "a1-804", german: "die Adresse", bengali: "ঠিকানা", example: "Meine Adresse ist neu." },
  { id: "a1-805", german: "das Geburtsdatum", bengali: "জন্ম তারিখ", example: "Mein Geburtsdatum ist im Mai." },
  { id: "a1-806", german: "der Geburtsort", bengali: "জন্মস্থান", example: "Mein Geburtsort ist Dhaka." },
  { id: "a1-807", german: "die Nationalität", bengali: "জাতীয়তা", example: "Meine Nationalität ist bangladeschisch." },
  { id: "a1-808", german: "das Alter", bengali: "বয়স", example: "Mein Alter ist 25." },
  { id: "a1-809", german: "verheiratet", bengali: "বিবাহিত", example: "Sie ist verheiratet." },
  { id: "a1-810", german: "ledig", bengali: "অবিবাহিত", example: "Er ist noch ledig." },
  { id: "a1-811", german: "der Ausweis", bengali: "পরিচয়পত্র", example: "Mein Ausweis ist neu." },
  { id: "a1-812", german: "der Pass", bengali: "পাসপোর্ট", example: "Mein Pass ist neu." },
  { id: "a1-813", german: "das Formular", bengali: "ফর্ম", example: "Füllen Sie das Formular aus." },
  { id: "a1-814", german: "die Unterschrift", bengali: "স্বাক্ষর", example: "Die Unterschrift fehlt." },
  { id: "a1-815", german: "unterschreiben", bengali: "স্বাক্ষর করা", example: "Ich unterschreibe hier." },
  { id: "a1-816", german: "die Telefonnummer", bengali: "ফোন নম্বর", example: "Wie ist Ihre Telefonnummer?" },
  { id: "a1-817", german: "die E-Mail-Adresse", bengali: "ইমেইল ঠিকানা", example: "Meine E-Mail-Adresse ist neu." },
  { id: "a1-818", german: "der Wohnort", bengali: "বসবাসের স্থান", example: "Mein Wohnort ist Berlin." },
  { id: "a1-819", german: "die Sprache", bengali: "ভাষা", example: "Welche Sprache sprechen Sie?" },
  { id: "a1-820", german: "die Muttersprache", bengali: "মাতৃভাষা", example: "Meine Muttersprache ist Bangla." },

  // Sub-Level 42 — Internet & Apps II (821–840)
  { id: "a1-821", german: "die Suchmaschine", bengali: "সার্চ ইঞ্জিন", example: "Ich nutze eine Suchmaschine." },
  { id: "a1-822", german: "die Datei", bengali: "ফাইল", example: "Die Datei ist groß." },
  { id: "a1-823", german: "der Ordner", bengali: "ফোল্ডার", example: "Der Ordner ist leer." },
  { id: "a1-824", german: "das Konto", bengali: "একাউন্ট", example: "Mein Konto ist neu." },
  { id: "a1-825", german: "sich anmelden", bengali: "লগইন করা", example: "Ich melde mich an." },
  { id: "a1-826", german: "sich abmelden", bengali: "লগআউট করা", example: "Ich melde mich ab." },
  { id: "a1-827", german: "registrieren", bengali: "নিবন্ধন করা", example: "Ich registriere mich." },
  { id: "a1-828", german: "die Einstellung", bengali: "সেটিংস", example: "Die Einstellung ist falsch." },
  { id: "a1-829", german: "der Bildschirm", bengali: "স্ক্রিন", example: "Der Bildschirm ist kaputt." },
  { id: "a1-830", german: "die Tastatur", bengali: "কিবোর্ড", example: "Die Tastatur ist neu." },
  { id: "a1-831", german: "die Maus", bengali: "মাউস (কম্পিউটার)", example: "Die Maus funktioniert nicht." },
  { id: "a1-832", german: "das Update", bengali: "আপডেট", example: "Das Update ist wichtig." },
  { id: "a1-833", german: "die Batterie", bengali: "ব্যাটারি", example: "Die Batterie ist leer." },
  { id: "a1-834", german: "aufladen", bengali: "চার্জ করা", example: "Ich lade mein Handy auf." },
  { id: "a1-835", german: "das Kabel", bengali: "তার/কেবল", example: "Das Kabel ist kurz." },
  { id: "a1-836", german: "die Kamera", bengali: "ক্যামেরা", example: "Die Kamera ist neu." },
  { id: "a1-837", german: "das Mikrofon", bengali: "মাইক্রোফোন", example: "Das Mikrofon funktioniert nicht." },
  { id: "a1-838", german: "die Lautstärke", bengali: "শব্দের তীব্রতা", example: "Die Lautstärke ist zu hoch." },
  { id: "a1-839", german: "online", bengali: "অনলাইন", example: "Ich bin gerade online." },
  { id: "a1-840", german: "offline", bengali: "অফলাইন", example: "Mein Handy ist offline." },

  // Sub-Level 43 — Sprachen & Länder (841–860)
  { id: "a1-841", german: "Deutschland", bengali: "জার্মানি", example: "Deutschland ist schön." },
  { id: "a1-842", german: "Bangladesch", bengali: "বাংলাদেশ", example: "Bangladesch ist meine Heimat." },
  { id: "a1-843", german: "Indien", bengali: "ভারত", example: "Indien ist sehr groß." },
  { id: "a1-844", german: "Österreich", bengali: "অস্ট্রিয়া", example: "Österreich liegt in Europa." },
  { id: "a1-845", german: "die Schweiz", bengali: "সুইজারল্যান্ড", example: "Die Schweiz ist klein." },
  { id: "a1-846", german: "Frankreich", bengali: "ফ্রান্স", example: "Frankreich ist bekannt." },
  { id: "a1-847", german: "England", bengali: "ইংল্যান্ড", example: "England liegt in Europa." },
  { id: "a1-848", german: "Amerika", bengali: "আমেরিকা", example: "Amerika ist groß." },
  { id: "a1-849", german: "Deutsch", bengali: "জার্মান (ভাষা)", example: "Ich lerne Deutsch." },
  { id: "a1-850", german: "Englisch", bengali: "ইংরেজি", example: "Sie spricht Englisch." },
  { id: "a1-851", german: "Bengalisch", bengali: "বাংলা (ভাষা)", example: "Meine Muttersprache ist Bengalisch." },
  { id: "a1-852", german: "Französisch", bengali: "ফ্রেঞ্চ", example: "Er lernt Französisch." },
  { id: "a1-853", german: "Spanisch", bengali: "স্প্যানিশ", example: "Sie lernt Spanisch." },
  { id: "a1-854", german: "Arabisch", bengali: "আরবি", example: "Er spricht Arabisch." },
  { id: "a1-855", german: "Hindi", bengali: "হিন্দি", example: "Sie spricht Hindi." },
  { id: "a1-856", german: "der Ausländer", bengali: "বিদেশি (পুরুষ)", example: "Der Ausländer lernt Deutsch." },
  { id: "a1-857", german: "die Ausländerin", bengali: "বিদেশি (মহিলা)", example: "Die Ausländerin spricht gut." },
  { id: "a1-858", german: "das Land", bengali: "দেশ", example: "Welches Land besuchst du?" },
  { id: "a1-859", german: "die Hauptstadt", bengali: "রাজধানী", example: "Berlin ist die Hauptstadt." },
  { id: "a1-860", german: "der Kontinent", bengali: "মহাদেশ", example: "Europa ist ein Kontinent." },

  // Sub-Level 44 — Freizeit-Aktivitäten II (861–880)
  { id: "a1-861", german: "das Picknick", bengali: "পিকনিক", example: "Wir machen ein Picknick." },
  { id: "a1-862", german: "der Ausflug", bengali: "ভ্রমণ/এক্সকার্শন", example: "Der Ausflug war toll." },
  { id: "a1-863", german: "das Konzert", bengali: "কনসার্ট", example: "Das Konzert war toll." },
  { id: "a1-864", german: "das Theater", bengali: "থিয়েটার", example: "Das Theater ist bekannt." },
  { id: "a1-865", german: "die Ausstellung", bengali: "প্রদর্শনী", example: "Die Ausstellung ist interessant." },
  { id: "a1-866", german: "der Zoo", bengali: "চিড়িয়াখানা", example: "Der Zoo ist groß." },
  { id: "a1-867", german: "das Museum", bengali: "জাদুঘর", example: "Das Museum ist interessant." },
  { id: "a1-868", german: "spazieren gehen", bengali: "হাঁটতে যাওয়া", example: "Ich gehe gern spazieren." },
  { id: "a1-869", german: "wandern", bengali: "হাইকিং করা", example: "Wir wandern im Wald." },
  { id: "a1-870", german: "angeln", bengali: "মাছ ধরা", example: "Er angelt am See." },
  { id: "a1-871", german: "zelten", bengali: "তাঁবুতে থাকা", example: "Wir zelten im Wald." },
  { id: "a1-872", german: "das Brettspiel", bengali: "বোর্ড গেম", example: "Das Brettspiel macht Spaß." },
  { id: "a1-873", german: "Karten spielen", bengali: "কার্ড খেলা", example: "Wir spielen gern Karten." },
  { id: "a1-874", german: "das Puzzle", bengali: "পাজল", example: "Das Puzzle ist schwer." },
  { id: "a1-875", german: "die Bibliothek besuchen", bengali: "গ্রন্থাগারে যাওয়া", example: "Ich besuche die Bibliothek." },
  { id: "a1-876", german: "schwimmen gehen", bengali: "সাঁতার কাটতে যাওয়া", example: "Wir gehen schwimmen." },
  { id: "a1-877", german: "Rad fahren", bengali: "সাইকেল চালানো", example: "Ich fahre gern Rad." },
  { id: "a1-878", german: "Musik hören", bengali: "গান শোনা", example: "Ich höre gern Musik." },
  { id: "a1-879", german: "ins Kino gehen", bengali: "সিনেমায় যাওয়া", example: "Wir gehen ins Kino." },
  { id: "a1-880", german: "die Freizeit", bengali: "অবসর সময়", example: "Meine Freizeit ist kurz." },

  // Sub-Level 45 — Essen & Restaurant II (881–900)
  { id: "a1-881", german: "das Frühstück", bengali: "সকালের নাস্তা", example: "Das Frühstück ist fertig." },
  { id: "a1-882", german: "das Mittagessen", bengali: "দুপুরের খাবার", example: "Das Mittagessen schmeckt gut." },
  { id: "a1-883", german: "das Abendessen", bengali: "রাতের খাবার", example: "Das Abendessen ist fertig." },
  { id: "a1-884", german: "der Snack", bengali: "নাস্তা/স্ন্যাক", example: "Ich esse einen Snack." },
  { id: "a1-885", german: "das Gemüse", bengali: "শাকসবজি", example: "Das Gemüse ist gesund." },
  { id: "a1-886", german: "die Kartoffel", bengali: "আলু", example: "Die Kartoffel ist weich." },
  { id: "a1-887", german: "die Tomate", bengali: "টমেটো", example: "Die Tomate ist rot." },
  { id: "a1-888", german: "die Gurke", bengali: "শসা", example: "Die Gurke ist frisch." },
  { id: "a1-889", german: "die Zwiebel", bengali: "পেঁয়াজ", example: "Die Zwiebel ist scharf." },
  { id: "a1-890", german: "der Knoblauch", bengali: "রসুন", example: "Der Knoblauch riecht stark." },
  { id: "a1-891", german: "das Öl", bengali: "তেল", example: "Das Öl ist heiß." },
  { id: "a1-892", german: "der Pfeffer", bengali: "গোলমরিচ", example: "Der Pfeffer ist scharf." },
  { id: "a1-893", german: "die Schokolade", bengali: "চকোলেট", example: "Die Schokolade ist süß." },
  { id: "a1-894", german: "das Eis", bengali: "আইসক্রিম", example: "Das Eis schmeckt gut." },
  { id: "a1-895", german: "der Honig", bengali: "মধু", example: "Der Honig ist süß." },
  { id: "a1-896", german: "die Nudel", bengali: "নুডলস", example: "Die Nudel ist lecker." },
  { id: "a1-897", german: "die Suppe", bengali: "স্যুপ", example: "Die Suppe ist heiß." },
  { id: "a1-898", german: "der Joghurt", bengali: "দই", example: "Der Joghurt ist lecker." },
  { id: "a1-899", german: "das Sandwich", bengali: "স্যান্ডউইচ", example: "Ich esse ein Sandwich." },
  { id: "a1-900", german: "vegetarisch essen", bengali: "নিরামিষ খাওয়া", example: "Ich esse vegetarisch." },

  // Sub-Level 46 — Alltagsphrasen & Höflichkeit (901–920)
  { id: "a1-901", german: "Entschuldigung", bengali: "মাফ করবেন", example: "Entschuldigung, wo ist der Bahnhof?" },
  { id: "a1-902", german: "Es tut mir leid", bengali: "আমি দুঃখিত", example: "Es tut mir leid!" },
  { id: "a1-903", german: "Kein Problem", bengali: "কোনো সমস্যা নেই", example: "Kein Problem!" },
  { id: "a1-904", german: "Wie bitte?", bengali: "আবার বলবেন?", example: "Wie bitte? Ich habe das nicht verstanden." },
  { id: "a1-905", german: "Natürlich", bengali: "অবশ্যই", example: "Natürlich helfe ich dir." },
  { id: "a1-906", german: "Genau", bengali: "ঠিক এই রকম", example: "Genau! Das stimmt." },
  { id: "a1-907", german: "Vielleicht", bengali: "হয়তো", example: "Vielleicht komme ich morgen." },
  { id: "a1-908", german: "Leider", bengali: "দুর্ভাগ্যবশত", example: "Leider kann ich nicht kommen." },
  { id: "a1-909", german: "Herzlichen Glückwunsch", bengali: "আন্তরিক অভিনন্দন", example: "Herzlichen Glückwunsch!" },
  { id: "a1-910", german: "Gute Besserung", bengali: "দ্রুত সুস্থ হও", example: "Gute Besserung!" },
  { id: "a1-911", german: "Viel Erfolg", bengali: "শুভকামনা", example: "Viel Erfolg bei der Prüfung!" },
  { id: "a1-912", german: "Viel Spaß", bengali: "মজা করো", example: "Viel Spaß im Urlaub!" },
  { id: "a1-913", german: "Alles Gute", bengali: "সব শুভ হোক", example: "Alles Gute zum Geburtstag!" },
  { id: "a1-914", german: "Guten Appetit", bengali: "খাওয়া শুরু করুন", example: "Guten Appetit!" },
  { id: "a1-915", german: "Gute Nacht", bengali: "শুভ রাত্রি", example: "Gute Nacht! Schlaf gut!" },
  { id: "a1-916", german: "Bis bald", bengali: "শীঘ্রই দেখা হবে", example: "Bis bald!" },
  { id: "a1-917", german: "Bis später", bengali: "পরে দেখা হবে", example: "Bis später!" },
  { id: "a1-918", german: "Schade", bengali: "দুঃখজনক", example: "Schade, dass du nicht kommst." },
  { id: "a1-919", german: "Macht nichts", bengali: "কিছু হয়নি", example: "Macht nichts, kein Problem." },
  { id: "a1-920", german: "Stimmt", bengali: "ঠিক/সত্যি", example: "Das stimmt." },

  // Sub-Level 47 — Allgemeine Nomen I (921–940)
  { id: "a1-921", german: "das Problem", bengali: "সমস্যা", example: "Das Problem ist gelöst." },
  { id: "a1-922", german: "die Lösung", bengali: "সমাধান", example: "Die Lösung ist einfach." },
  { id: "a1-923", german: "die Idee", bengali: "ধারণা", example: "Das ist eine gute Idee." },
  { id: "a1-924", german: "die Frage", bengali: "প্রশ্ন", example: "Die Frage ist schwer." },
  { id: "a1-925", german: "die Antwort", bengali: "উত্তর", example: "Die Antwort ist richtig." },
  { id: "a1-926", german: "der Grund", bengali: "কারণ", example: "Der Grund ist klar." },
  { id: "a1-927", german: "das Ziel", bengali: "লক্ষ্য", example: "Mein Ziel ist Deutsch zu lernen." },
  { id: "a1-928", german: "der Plan", bengali: "পরিকল্পনা", example: "Der Plan ist gut." },
  { id: "a1-929", german: "die Möglichkeit", bengali: "সম্ভাবনা", example: "Es gibt viele Möglichkeiten." },
  { id: "a1-930", german: "die Entscheidung", bengali: "সিদ্ধান্ত", example: "Die Entscheidung ist schwer." },
  { id: "a1-931", german: "die Information", bengali: "তথ্য", example: "Die Information ist wichtig." },
  { id: "a1-932", german: "die Nachricht", bengali: "খবর/বার্তা", example: "Die Nachricht ist gut." },
  { id: "a1-933", german: "die Geschichte", bengali: "গল্প/ইতিহাস", example: "Die Geschichte ist interessant." },
  { id: "a1-934", german: "die Erfahrung", bengali: "অভিজ্ঞতা", example: "Ich habe viel Erfahrung." },
  { id: "a1-935", german: "die Erinnerung", bengali: "স্মৃতি", example: "Die Erinnerung ist schön." },
  { id: "a1-936", german: "der Traum", bengali: "স্বপ্ন", example: "Mein Traum wird wahr." },
  { id: "a1-937", german: "die Hoffnung", bengali: "আশা", example: "Die Hoffnung bleibt." },
  { id: "a1-938", german: "die Angst", bengali: "ভয়", example: "Ich habe keine Angst." },
  { id: "a1-939", german: "die Liebe", bengali: "প্রেম/ভালোবাসা", example: "Die Liebe ist schön." },
  { id: "a1-940", german: "die Freundschaft", bengali: "বন্ধুত্ব", example: "Die Freundschaft ist wichtig." },

  // Sub-Level 48 — Allgemeine Nomen II (941–960)
  { id: "a1-941", german: "die Welt", bengali: "পৃথিবী", example: "Die Welt ist groß." },
  { id: "a1-942", german: "das Leben", bengali: "জীবন", example: "Das Leben ist schön." },
  { id: "a1-943", german: "die Zukunft", bengali: "ভবিষ্যৎ", example: "Die Zukunft ist unbekannt." },
  { id: "a1-944", german: "die Vergangenheit", bengali: "অতীত", example: "Die Vergangenheit ist vorbei." },
  { id: "a1-945", german: "die Gegenwart", bengali: "বর্তমান", example: "Die Gegenwart ist wichtig." },
  { id: "a1-946", german: "die Wahrheit", bengali: "সত্য", example: "Die Wahrheit ist wichtig." },
  { id: "a1-947", german: "die Lüge", bengali: "মিথ্যা", example: "Das ist eine Lüge." },
  { id: "a1-948", german: "das Geheimnis", bengali: "গোপনীয়তা", example: "Das ist ein Geheimnis." },
  { id: "a1-949", german: "die Regel", bengali: "নিয়ম", example: "Die Regel ist klar." },
  { id: "a1-950", german: "die Freiheit", bengali: "স্বাধীনতা", example: "Freiheit ist wichtig." },
  { id: "a1-951", german: "die Gesellschaft", bengali: "সমাজ", example: "Die Gesellschaft ist vielfältig." },
  { id: "a1-952", german: "die Kultur", bengali: "সংস্কৃতি", example: "Die Kultur ist interessant." },
  { id: "a1-953", german: "die Tradition", bengali: "প্রথা", example: "Die Tradition ist alt." },
  { id: "a1-954", german: "das Fest", bengali: "উৎসব", example: "Das Fest ist schön." },
  { id: "a1-955", german: "die Religion", bengali: "ধর্ম", example: "Die Religion ist persönlich." },
  { id: "a1-956", german: "die Politik", bengali: "রাজনীতি", example: "Die Politik ist kompliziert." },
  { id: "a1-957", german: "die Wirtschaft", bengali: "অর্থনীতি", example: "Die Wirtschaft wächst." },
  { id: "a1-958", german: "die Umwelt", bengali: "পরিবেশ", example: "Die Umwelt ist wichtig." },
  { id: "a1-959", german: "die Wissenschaft", bengali: "বিজ্ঞান", example: "Die Wissenschaft ist faszinierend." },
  { id: "a1-960", german: "die Technologie", bengali: "প্রযুক্তি", example: "Die Technologie verändert sich schnell." },

  // Sub-Level 49 — Mengen & Maße (961–980)
  { id: "a1-961", german: "viel", bengali: "অনেক", example: "Ich habe viel Arbeit." },
  { id: "a1-962", german: "wenig", bengali: "কম", example: "Ich habe wenig Zeit." },
  { id: "a1-963", german: "alle", bengali: "সবাই", example: "Alle sind hier." },
  { id: "a1-964", german: "niemand", bengali: "কেউ না", example: "Niemand ist hier." },
  { id: "a1-965", german: "jemand", bengali: "কেউ", example: "Jemand ist an der Tür." },
  { id: "a1-966", german: "etwas", bengali: "কিছু", example: "Ich brauche etwas Wasser." },
  { id: "a1-967", german: "nichts", bengali: "কিছু না", example: "Ich habe nichts gegessen." },
  { id: "a1-968", german: "mehr", bengali: "বেশি", example: "Ich brauche mehr Zeit." },
  { id: "a1-969", german: "weniger", bengali: "কম (তুলনায়)", example: "Ich brauche weniger Zucker." },
  { id: "a1-970", german: "genug", bengali: "যথেষ্ট", example: "Das ist genug." },
  { id: "a1-971", german: "die Hälfte", bengali: "অর্ধেক", example: "Ich nehme die Hälfte." },
  { id: "a1-972", german: "das Kilo", bengali: "কিলোগ্রাম", example: "Ich kaufe ein Kilo Reis." },
  { id: "a1-973", german: "der Liter", bengali: "লিটার", example: "Ich kaufe einen Liter Milch." },
  { id: "a1-974", german: "der Meter", bengali: "মিটার", example: "Der Tisch ist ein Meter lang." },
  { id: "a1-975", german: "das Gramm", bengali: "গ্রাম", example: "Ich brauche zweihundert Gramm Zucker." },
  { id: "a1-976", german: "das Paar", bengali: "জোড়া", example: "Ich kaufe ein Paar Schuhe." },
  { id: "a1-977", german: "das Dutzend", bengali: "ডজন", example: "Ich kaufe ein Dutzend Eier." },
  { id: "a1-978", german: "die Tüte", bengali: "ব্যাগ/থলে", example: "Ich brauche eine Tüte." },
  { id: "a1-979", german: "die Packung", bengali: "প্যাকেট", example: "Die Packung ist leer." },
  { id: "a1-980", german: "das Stück", bengali: "টুকরা", example: "Ich nehme ein Stück Kuchen." },

  // Sub-Level 50 — Sonstige wichtige Wörter (981–1000)
  { id: "a1-981", german: "der Mensch", bengali: "মানুষ", example: "Der Mensch ist sozial." },
  { id: "a1-982", german: "die Person", bengali: "ব্যক্তি", example: "Die Person ist freundlich." },
  { id: "a1-983", german: "die Leute", bengali: "মানুষজন", example: "Die Leute sind nett." },
  { id: "a1-984", german: "jemand anders", bengali: "অন্য কেউ", example: "Frag jemand anders." },
  { id: "a1-985", german: "selbst", bengali: "নিজে", example: "Ich mache es selbst." },
  { id: "a1-986", german: "zusammen", bengali: "একসাথে", example: "Wir essen zusammen." },
  { id: "a1-987", german: "allein", bengali: "একা", example: "Ich bin allein." },
  { id: "a1-988", german: "gemeinsam", bengali: "সমষ্টিগতভাবে", example: "Wir lernen gemeinsam." },
  { id: "a1-989", german: "die Hilfe", bengali: "সাহায্য", example: "Danke für Ihre Hilfe." },
  { id: "a1-990", german: "helfen", bengali: "সাহায্য করা", example: "Ich helfe gern." },
  { id: "a1-991", german: "teilen", bengali: "ভাগ করা", example: "Ich teile mein Essen." },
  { id: "a1-992", german: "schenken", bengali: "উপহার দেওয়া", example: "Ich schenke ihr Blumen." },
  { id: "a1-993", german: "leihen", bengali: "ধার দেওয়া/নেওয়া", example: "Kannst du mir Geld leihen?" },
  { id: "a1-994", german: "zurückgeben", bengali: "ফেরত দেওয়া", example: "Ich gebe das Buch zurück." },
  { id: "a1-995", german: "versprechen", bengali: "প্রতিশ্রুতি দেওয়া", example: "Ich verspreche es dir." },
  { id: "a1-996", german: "erlauben", bengali: "অনুমতি দেওয়া", example: "Erlauben Sie mir zu fragen?" },
  { id: "a1-997", german: "verbieten", bengali: "নিষেধ করা", example: "Rauchen ist hier verboten." },
  { id: "a1-998", german: "die Erlaubnis", bengali: "অনুমতি", example: "Ich brauche die Erlaubnis." },
  { id: "a1-999", german: "die Regel befolgen", bengali: "নিয়ম মানা", example: "Wir befolgen die Regeln." },
  { id: "a1-1000", german: "das letzte Wort", bengali: "শেষ শব্দ", example: "Das ist das letzte Wort dieser Liste!" },
];
